<?php

use yii\db\Migration;

class m180202_175508_transl_a_menu extends Migration
{

	public function safeUp()
	{
		$sql = "
            set foreign_key_checks=0;
			TRUNCATE TABLE  `moha`.`menu`;
			TRUNCATE TABLE  `moha`.`message`;
			TRUNCATE TABLE  `moha`.`source_message`;

		INSERT INTO `moha`.`menu` (`id`, `name`, `url`, `icon`, `description`, `deleted`, `menugroup_id`, `menu_parent_id`, `input_id`, `input_dt_stamp`, `position`, `table_name`, `has_province`)
		VALUES
			(1, 'ກົມຈັດຕັ້ງ ແລະ ພະນັກງານ', NULL, NULL, 'ກົມຈັດຕັ້ງ ແລະ ພະນັກງານ', 0, NULL, 3, NULL, '2017-09-03 18:41:53', 14, NULL, NULL),
			(2, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ ແຕ່ຊັ້ນ I ເຖິງ ຊັ້ນ V', 'stat-officer-salary', NULL, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ ແຕ່ຊັ້ນ I ເຖິງ ຊັ້ນ V', 0, NULL, 1, NULL, '2017-09-03 18:45:05', 1, 'stat_officer_salary', NULL),
			(3, 'ປ້ອນຂໍ້ມູນ', '#', NULL, 'ປ້ອນຂໍ້ມູນ', 0, NULL, 0, 1, '2017-09-25 20:17:01', 1, '#', NULL),
			(13, 'ສະຖາບັນຄົ້ນຄວ້າວິທະຍາສາດການປົກຄອງ ແລະ ຝຶກອົບຮົມ', NULL, NULL, 'ສະຖາບັນຄົ້ນຄວ້າວິທະຍາສາດການປົກຄອງ ແລະ ຝຶກອົບຮົມ', 0, NULL, 3, NULL, '2017-09-03 18:45:38', 7, NULL, NULL),
			(14, 'ຕາຕະລາງສະຖິຕິການພັດທະນາຫຼັກສູດເຝິກອົບຮົມລັດຖະກອນ', 'stat-course', NULL, 'ຕາຕະລາງສະຖິຕິການພັດທະນາຫຼັກສູດເຝິກອົບຮົມລັດຖະກອນ', 0, NULL, 13, NULL, '2017-09-03 18:47:12', 1, 'stat_course', NULL),
			(21, 'ກົມວຽກງານຊົນເຜົ່າ ແລະ ສາສະໜາ', NULL, NULL, 'ກົມວຽກງານຊົນເຜົ່າ ແລະ ສາສະໜາ', 0, NULL, 3, NULL, '2017-09-03 18:47:24', 3, NULL, NULL),
			(22, 'ສະຖິຕິປະຊາຊົນເຊື່ອຖືສາສະໜາ ແລະ ຄວາມເຊື່ອອື່ນໃນທົ່ວປະເທດ ', 'stat-religion', NULL, 'ສະຖິຕິປະຊາຊົນເຊື່ອຖືສາສະໜາ ແລະ ຄວາມເຊື່ອອື່ນໃນທົ່ວປະເທດ ', 0, NULL, 21, NULL, '2017-09-03 18:48:20', 2, 'stat_religion', 1),
			(23, 'ສະຖິຕິພະສົງ ແລະ ຄູສອນສາສະໜາ ໃນທົ່ວປະເທດ', 'stat-religion-teacher', NULL, 'ສະຖິຕິພະສົງ ແລະ ຄູສອນສາສະໜາ ໃນທົ່ວປະເທດ', 0, NULL, 21, NULL, '2017-09-03 18:48:20', 3, 'stat_religion_teacher', 1),
			(24, 'ສະຖິຕິສາສະນະສະຖານໃນທົ່ວປະເທດ', 'stat-religion-place', NULL, 'ສະຖິຕິສາສະນະສະຖານໃນທົ່ວປະເທດ', 0, NULL, 21, NULL, '2017-09-03 18:48:20', 4, 'stat_religion_place', 1),
			(25, 'ສະຖິຕິຊົນເຜົ່າໃນທົ່ວປະເທດ', 'stat-ethnic', NULL, 'ສະຖິຕິຊົນເຜົ່າໃນທົ່ວປະເທດ', 0, NULL, 21, NULL, '2017-09-03 18:48:20', 1, 'stat_ethnic', 1),
			(27, 'ກົມປະເມີນຜົນ ແລະ ພັດທະນາລັດຖະກອນ', NULL, NULL, 'ກົມປະເມີນຜົນ ແລະ ພັດທະນາລັດຖະກອນ', 0, NULL, 3, NULL, '2017-09-03 18:49:19', 6, NULL, NULL),
			(54, 'ກົມຄຸ້ມຄອງພົນລະເມືອງ', NULL, NULL, 'ກົມຄຸ້ມຄອງພົນລະເມືອງ', 0, NULL, 3, NULL, '2017-09-03 18:50:38', 4, NULL, NULL),
			(56, 'ການເກັບກຳສະຖິຕິການເໜັງຕີງຂອງພົນລະເມືອງ ຂອງກະຊວງພາຍໃນ ປະຈຳປີ', 'stat-population-movement', NULL, 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງລາວທົ່ວປະເທດ', 0, NULL, 54, NULL, '2017-09-03 18:51:25', 1, 'stat_population_movement', 1),
			(57, 'ການສົມທຽບສະຖິຕິເໜັງຕີງຂອງພົນລະເມືອງຂອງປີ', 'stat-population-movement-chart', NULL, 'ການສົມທຽບສະຖິຕິເໜັງຕີງຂອງພົນລະເມືອງຂອງປີ', 1, NULL, 54, NULL, '2017-09-03 18:51:25', 2, 'stat_population_movement_chart', NULL),
			(67, 'ກົມການປົກຄອງທ້ອງຖິ່ນ', NULL, NULL, 'ກົມການປົກຄອງທ້ອງຖິ່ນ', 0, NULL, 3, NULL, '2017-09-03 18:51:37', 2, NULL, NULL),
			(71, 'ຕາຕະລາງສັງລວມຂໍ້ມູນກ່ຽວກັບເມືອງ, ບ້ານ ທົ່ວແຂວງ', 'stat-local-admin', NULL, 'ຕາຕະລາງສັງລວມຂໍ້ມູນກ່ຽວກັບເມືອງ, ບ້ານ ທົ່ວແຂວງ', 0, NULL, 67, NULL, '2017-09-03 18:52:20', NULL, 'stat_local_admin', 1),
			(79, 'ກົມພັດທະນາ ແລະ ການບໍລິຫານລັດ', NULL, NULL, 'ກົມພັດທະນາ ແລະ ການບໍລິຫານລັດ', 0, NULL, 3, NULL, '2017-09-03 18:52:28', 1, NULL, NULL),
			(80, 'ສະຖິຕິໂຄງປະກອບກົງຈັກຂອງລັດຖະບານ', 'ministry', NULL, 'ສະຖິຕິກົງຈັກຂອງລັດຖະບານ.... ກະຊວງ ..... ອົງການລັດທຽບເທົ່າ', 0, NULL, 79, NULL, '2017-09-03 18:53:04', 1, 'ministry', NULL),
			(81, 'ສະຖິຕິບັນດາຫົວໜ່ວຍການຈັດຕັ້ງ (ກົມ, ສະຖາບັນ, ສູນ ແລະ ທຽບເທົ່າກົມ)', 'stat-goverment-unit', NULL, 'ສະຖິຕິບັນດາຫົວໜ່ວຍການຈັດຕັ້ງ (ກົມ, ສະຖາບັນ, ສູນ ແລະ ທຽບເທົ່າກົມ)', 0, NULL, 79, NULL, '2017-09-03 18:53:04', 2, 'stat_goverment_unit', NULL),
			(82, 'ສະຖິຕິບັນດານິຕິກຳຂະແໜງພາຍໃນທີ່ກຳລັງປັບປຸງ ແລະ ຮ່າງຂຶ້ນໃໝ່', 'stat-legal', NULL, 'ສະຖິຕິບັນດານິຕິກຳຂະແໜງພາຍໃນທີ່ກຳລັງປັບປຸງ ແລະ ຮ່າງຂຶ້ນໃໝ່', 0, NULL, 79, NULL, '2017-09-03 18:53:04', 4, 'stat_legal', NULL),
			(83, 'ສະຖິຕິໜ່ວຍງານຈັດຕັ້ງປະຕິບັດກົນໄກການບໍລິການຜ່ານປະຕູດຽວ', 'stat-single-gateway-implementation', NULL, 'ສະຖິຕິໜ່ວຍງານຈັດຕັ້ງປະຕິບັດກົນໄກການບໍລິການຜ່ານປະຕູດຽວ', 0, NULL, 79, NULL, '2017-09-03 18:53:04', 3, 'stat_single_gateway_implementation', NULL),
			(84, 'ສະຖິຕິສະມາຄົມ/ມູນນິທິໃນທົ່ວປະເທດ', 'stat-association-foundation', NULL, 'ສະຖິຕິສະມາຄົມ/ມູນນິທິໃນທົ່ວປະເທດ', 0, NULL, 79, NULL, '2017-09-03 18:53:04', 5, 'stat_association_foundation', NULL),
			(86, 'ກົມສຳເນົາເອກະສານແຫ່ງຊາດ', '', NULL, 'ກົມສຳເນົາເອກະສານແຫ່ງຊາດ', 0, NULL, 3, NULL, '2017-09-03 18:53:18', 8, '', NULL),
			(87, 'ສະຖິຕິການສັງລວມ ການສຳເນົາ', 'stat-copy', NULL, 'ສະຖິຕິການສັງລວມ ການສຳເນົາ', 0, NULL, 86, NULL, '2017-09-03 18:54:01', 2, 'stat_copy', NULL),
			(88, 'ສະຖິຕິການທ້ອນໂຮມເອກະສານທີ່ມີຄວາມສຳຄັນແຫ່ງຊາດ', 'stat-document', NULL, 'ສະຖິຕິການທ້ອນໂຮມເອກະສານທີ່ມີຄວາມສຳຄັນແຫ່ງຊາດ', 0, NULL, 86, NULL, '2017-09-03 18:54:01', 1, 'stat_document', NULL),
			(89, 'ກົມແຜນທີ່ແຫ່ງຊາດ', NULL, NULL, 'ກົມແຜນທີ່ແຫ່ງຊາດ', 0, NULL, 3, NULL, '2017-09-03 18:54:01', 10, NULL, NULL),
			(90, 'ສະຖິຕິການເຄື່ອນໄຫວວຽກງານສຳຫຼວດປະຈຳປີ ......', 'stat-explore', NULL, 'ສະຖິຕິການເຄື່ອນໄຫວວຽກງານສຳຫຼວດປະຈຳປີ ......', 0, NULL, 89, NULL, '2017-09-03 18:55:00', 3, 'stat_explore', 1),
			(91, 'ສະຖິຕິການບໍລິການແຜນທີ່ມາດຕາສ່ວນ', 'stat-map-service', NULL, 'ສະຖິຕິການບໍລິການແຜນທີ່ມາດຕາສ່ວນ', 0, NULL, 89, NULL, '2017-09-03 18:55:00', 1, 'stat_map_service', NULL),
			(92, 'ສະຖິຕິການຜະລິດແຜນທີ່', 'stat-map-produce', NULL, 'ສະຖິຕິການຜະລິດແຜນທີ່', 0, NULL, 89, NULL, '2017-09-03 18:55:00', 2, 'stat_map_produce', NULL),
			(93, 'ສູນສຳຫຼວດວັດແທກ ແລະ ແຜນທີ່', NULL, NULL, 'ສູນສຳຫຼວດວັດແທກ ແລະ ແຜນທີ່', 0, NULL, 3, NULL, '2017-09-03 18:55:01', 11, NULL, NULL),
			(94, 'ສະຖິຕິການສຳຫຼວດວັດແທກ ແລະ ວຽກງານການພິມ', 'stat-explore', NULL, 'ສະຖິຕິການສຳຫຼວດວັດແທກ ແລະ ວຽກງານການພິມ', 0, NULL, 93, NULL, '2017-09-03 18:55:28', NULL, 'stat_explore', 1),
			(95, 'ກົມແຂ່ງຂັນ ແລະ ຍ້ອງຍໍ', NULL, NULL, 'ກົມແຂ່ງຂັນ ແລະ ຍ້ອງຍໍ', 0, NULL, 3, NULL, '2017-09-03 18:55:29', 9, NULL, NULL),
			(96, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ', 'stat-victorycoin-province', NULL, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 4, 'stat_victorycoin_province', 1),
			(97, 'ປະເພດຫຼຽນກາສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງ', 'stat-govcoin-province', NULL, 'ປະເພດຫຼຽນກາສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 10, 'stat_govcoin_province', 1),
			(98, 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ', 'stat-govcoin-ministry', NULL, 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 5, 'stat_govcoin_ministry', NULL),
			(99, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ', 'stat-victoryoversea-ministry', NULL, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 7, 'stat_victoryoversea_ministry', NULL),
			(100, 'ປະເພດຫຼຽນໄຊຊັ້ນສູງ ແລະ ຫຼຽນນາມມະຍົດຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ', 'stat-highcoin-ministry', NULL, 'ປະເພດຫຼຽນໄຊຊັ້ນສູງ ແລະ ຫຼຽນນາມມະຍົດຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 1, 'stat_highcoin_ministry', NULL),
			(101, 'ປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ', 'stat-highoversea-ministry', NULL, 'ປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 6, 'stat_highoversea_ministry', NULL),
			(102, 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ', 'stat-govoversea-ministry', NULL, 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 9, 'stat_govoversea_ministry', NULL),
			(103, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ', 'stat-victoryoversea-province', NULL, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 8, 'stat_victoryoversea_province', 1),
			(104, 'ປະເພດຫຼຽນນາມມະຍົດຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ', 'stat-hornorcoin-province', NULL, 'ປະເພດຫຼຽນນາມມະຍົດຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 2, 'stat_hornorcoin_province', 1),
			(105, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ', 'stat-victorycoin-ministry', NULL, 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ', 0, NULL, 95, NULL, '2017-09-03 19:00:16', 3, 'stat_victorycoin_ministry', NULL),
			(106, 'ກົມແຜນການ ແລະ ການຮ່ວມມື', NULL, NULL, 'ກົມແຜນການ ແລະ ການຮ່ວມມື', 0, NULL, 3, NULL, '2017-09-03 19:00:17', 13, NULL, NULL),
			(109, 'ກົມຄຸ້ມຄອງລັດຖະກອນ', NULL, NULL, 'ກົມຄຸ້ມຄອງລັດຖະກອນ', 0, NULL, 3, NULL, '2017-09-03 19:01:13', 5, NULL, NULL),
			(110, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນໃນທົ່ວປະເທດ', 'stat-officer', NULL, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນໃນທົ່ວປະເທດ', 0, NULL, 109, NULL, '2017-09-03 19:05:41', 1, 'stat_officer', NULL),
			(111, 'ແຜນຄວາມຕ້ອງການລັດຖະກອນໃໝ່', 'stat-officer-need', NULL, 'ແຜນຄວາມຕ້ອງການລັດຖະກອນໃໝ່', 0, NULL, 109, NULL, '2017-09-03 19:06:06', 8, 'stat_officer_need', NULL),
			(112, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນວິຊາສະເພາະ', 'stat-officer-degree', NULL, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນວິຊາສະເພາະ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 3, 'stat_officer_degree', NULL),
			(113, 'ຕາຕະລາງສັງລວມລັດຖະກອນແຍກຕາມເກນອາຍຸ', 'stat-officer-age', NULL, 'ຕາຕະລາງສັງລວມລັດຖະກອນແຍກຕາມເກນອາຍຸ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 2, 'stat_officer_age', NULL),
			(114, 'ສະຖິຕິລວມຂອງອົງການຈັດຕັ້ງຂັ້ນສູນກາງ', 'stat-officer-org', NULL, 'ສະຖິຕິລວມຂອງອົງການຈັດຕັ້ງຂັ້ນສູນກາງ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 10, 'stat_officer_org', NULL),
			(115, 'ຈຳນວນລັດຖະກອນແຍກຕາມຕຳແໜ່ງບໍລິຫານປະເພດຕ່າງໆ', 'stat-officer-position', NULL, 'ຈຳນວນລັດຖະກອນແຍກຕາມຕຳແໜ່ງບໍລິຫານປະເພດຕ່າງໆ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 7, 'stat_officer_position', NULL),
			(116, 'ຈຳນວນລັດຖະກອນທີ່ເຂົ້າເພີ່ມໃນຮູບການຕ່າງໆ', 'stat-officer-add', NULL, 'ຈຳນວນລັດຖະກອນທີ່ເຂົ້າເພີ່ມໃນຮູບການຕ່າງໆ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 5, 'stat_officer_add', NULL),
			(117, 'ຈຳນວນລັດຖະກອນທີ່ອອກໃນຮູບການຕ່າງໆ', 'stat-officer-resign', NULL, 'ຈຳນວນລັດຖະກອນທີ່ອອກໃນຮູບການຕ່າງໆ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 4, 'stat_officer_resign', NULL),
			(118, 'ຈຳນວນພະນັກງານຕາມສັນຍາ', 'stat-officer-contract', NULL, 'ຈຳນວນພະນັກງານຕາມສັນຍາ', 0, NULL, 109, NULL, '2017-09-03 19:10:17', 6, 'stat_officer_contract', NULL),
			(119, 'ສະຖິຕິລັດຖະກອນລວມຂອງແຕ່ລະກະຊວງ, ອົງການທຽບເທົ່າກະຊວງ', 'stat-officer-ministry', NULL, 'ສະຖິຕິລັດຖະກອນລວມຂອງແຕ່ລະກະຊວງ, ອົງການທຽບເທົ່າກະຊວງ', 0, NULL, 109, NULL, '2017-09-03 19:10:18', 9, 'stat_officer_ministry', NULL),
			(120, 'ຫ້ອງການກະຊວງ', NULL, NULL, 'ຫ້ອງການກະຊວງ', 1, NULL, 3, NULL, '2017-09-19 08:37:26', 12, NULL, NULL),
			(122, 'ກົມກວດກາ', NULL, NULL, 'ກົມກວດກາ', 1, NULL, 3, NULL, '2017-09-19 08:43:44', 15, NULL, NULL),
			(441, 'ຜູ້ໃຊ້ລະບົບ', 'user/manageuser', NULL, 'ຜູ້ໃຊ້ລະບົບ', 0, NULL, 0, NULL, '2017-09-19 09:25:56', 16, 'user/manageuser', NULL),
			(442, 'ການກໍານົດສິດ', 'user/managerole', NULL, 'ການກໍານົດສິດ', 0, NULL, 0, NULL, '2017-09-19 09:27:25', 17, 'user/managerole', NULL),
			(443, 'ຕັ້ງຄ່າ', NULL, NULL, 'ຕັ້ງຄ່າ', 0, NULL, 0, NULL, '2017-09-19 09:27:34', 18, NULL, NULL),
			(444, 'ສົກປີ', 'phiscal-year', 'fa fa-circle-o', 'ສົກປີ', 0, 1, 443, 1, '2017-09-19 09:27:34', 1, 'phiscal_year', NULL),
			(445, 'ແປຄຳສັບ', 'message', '', 'ແປຄຳສັບ', 0, 1, 443, 1, '2017-09-19 09:27:34', 99, 'message', NULL),
			(446, 'ສະຖິຕິລັດຖະກອນລວມຂອງບັນດາແຂວງ/ນະຄອນຫຼວງ', 'stat-officer-province', NULL, 'ສະຖິຕິລັດຖະກອນລວມຂອງບັນດາແຂວງ/ນະຄອນຫຼວງ', 0, NULL, 109, NULL, '2017-09-25 19:11:04', 11, 'stat_officer_province', 1),
			(447, 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການ ຂອງບັນດາກະຊວງ, ອົງການທຽບເທົ່າ', 'stat-officer-ministry-add', NULL, 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການ ຂອງບັນດາກະຊວງ, ອົງການທຽບເທົ່າ', 0, NULL, 109, NULL, '2017-09-25 19:16:43', 12, 'stat_officer_ministry_add', NULL),
			(448, 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການອົງການຈັດຕັ້ງຂັ້ນສູນກາງ', 'stat-officer-organisation-add', NULL, 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການອົງການຈັດຕັ້ງຂັ້ນສູນກາງ', 0, NULL, 109, NULL, '2017-09-25 19:18:36', 13, 'stat_officer_organisation_add', NULL),
			(449, 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການທົ່ວແຂວງ ແລະ ນະຄອນຫຼວງໃນ ສປປ ລາວ', 'stat-officer-province-add', NULL, 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການທົ່ວແຂວງ ແລະ ນະຄອນຫຼວງໃນ ສປປ ລາວ', 0, NULL, 109, NULL, '2017-09-25 19:19:33', 14, 'stat_officer_province_add', 1),
			(450, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນກະຊວງທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 'stat-officer-ministry-train', NULL, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນກະຊວງທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 0, NULL, 27, NULL, '2017-09-25 19:22:58', 1, 'stat_officer_ministry_train', NULL),
			(451, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນອົງການທຽບເທົ່າທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 'stat-officer-organisation-train', NULL, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນອົງການທຽບເທົ່າທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 0, NULL, 27, NULL, '2017-09-25 19:24:15', 2, 'stat_officer_organisation_train', NULL),
			(452, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນທ້ອງຖິ່ນທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 'stat-officer-province-train', NULL, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນທ້ອງຖິ່ນທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 0, NULL, 27, NULL, '2017-09-25 19:25:30', 3, 'stat_officer_province_train', 1),
			(453, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນກະຊວງທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 'stat-officer-ministry-upgrade', NULL, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນກະຊວງທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 0, NULL, 27, NULL, '2017-09-25 19:27:21', 4, 'stat_officer_ministry_upgrade', NULL),
			(454, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນອົງການທຽບເທົ່າທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 'stat-officer-organisation-upgrade', NULL, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນອົງການທຽບເທົ່າທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 0, NULL, 27, NULL, '2017-09-25 19:28:50', 5, 'stat_officer_organisation_upgrade', NULL),
			(457, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນທ້ອງຖິ່ນທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 'stat-officer-province-upgrade', NULL, 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນທ້ອງຖິ່ນທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ', 0, NULL, 27, NULL, '2017-09-25 19:29:59', 6, 'stat_officer_province_upgrade', 1),
			(458, 'ສະຖາບັນຮ່ວມກັບພາກສ່ວນພາຍນອກຈັດເຝິກອົບຮົມ', 'stat-institute-train', NULL, 'ສະຖາບັນຮ່ວມກັບພາກສ່ວນພາຍນອກຈັດເຝິກອົບຮົມ', 0, NULL, 13, NULL, '2017-09-25 19:33:51', 2, 'stat_institute_train', NULL),
			(460, 'ສະຖິຕິສັງລວມສະຖາບັນຈັດກອງປະຊຸມ ແລະ ຝຶກອົບຮົມໃຫ້ບັນດາກະຊວງ, ອົງການຂັ້ນສູນກາງ ແລະ ທ້ອງຖິ່ນ', 'stat-institute-meeting', NULL, 'ສະຖິຕິສັງລວມສະຖາບັນຈັດກອງປະຊຸມ ແລະ ຝຶກອົບຮົມໃຫ້ບັນດາກະຊວງ, ອົງການຂັ້ນສູນກາງ ແລະ ທ້ອງຖິ່ນ', 0, NULL, 13, NULL, '2017-09-25 19:37:21', 3, 'stat_institute_meeting', NULL),
			(461, 'ສັງລວມສະຖິຕິສູນຄົ້ນຄວ້າວຽກງານການປົກຄອງ', 'stat-research', NULL, 'ສັງລວມສະຖິຕິສູນຄົ້ນຄວ້າວຽກງານການປົກຄອງ', 0, NULL, 13, NULL, '2017-09-25 19:39:45', 4, 'stat_research', NULL),
			(462, 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ', 'stat-govoversea-province', NULL, 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ', 0, NULL, 95, NULL, '2017-09-25 19:59:15', 11, 'stat_govoversea_province', 1),
			(463, 'ສະຖິຕິໂຄງການລົງທຶນຂອງລັດ', 'stat-investment', NULL, 'ສະຖິຕິໂຄງການລົງທຶນຂອງລັດ', 0, NULL, 89, NULL, '2017-09-25 20:05:03', 4, 'stat_investment', NULL),
			(464, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນ ແຍກຕາມວິຊາສະເພາະ', 'stat-officer-technical', NULL, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນ ແຍກຕາມວິຊາສະເພາະ', 0, NULL, 1, NULL, '2017-09-25 20:09:25', 2, 'stat_officer_technical', NULL),
			(465, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມເກນອາຍຸ', 'stat-officer-age-level', NULL, 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມເກນອາຍຸ', 0, NULL, 1, NULL, '2017-09-25 20:11:26', 3, 'stat_officer_age_level', NULL),
			(466, 'ຕາຕະລາງຈຳນວນລັດຖະກອນແຍກຕາມຊົນເຜົ່າ', 'stat-officer-ethnic', NULL, 'ຕາຕະລາງຈຳນວນລັດຖະກອນແຍກຕາມຊົນເຜົ່າ', 0, NULL, 1, NULL, '2017-09-25 20:12:20', 3, 'stat_officer_ethnic', NULL),
			(467, 'ສະຖິຕິຜູ້ທີ່ໄດ້ຮັບຕຳແໜ່ງບໍລິຫານປະເພດຕ່າງໆ', 'stat-position', NULL, 'ສະຖິຕິຜູ້ທີ່ໄດ້ຮັບຕຳແໜ່ງບໍລິຫານປະເພດຕ່າງໆ', 0, NULL, 1, NULL, '2017-09-25 20:14:05', 4, 'stat_position', NULL),
			(469, 'ຈຳນວນລັດຖະກອນເພີ່ມເຂົ້າໃໝ່ໃນຮູບການຕ່າງໆ', 'stat-officer-new', NULL, 'ຈຳນວນລັດຖະກອນເພີ່ມເຂົ້າໃໝ່ໃນຮູບການຕ່າງໆ', 0, NULL, 1, NULL, '2017-09-25 20:15:04', 5, 'stat_officer_new', NULL),
			(471, 'ຈຳນວນລັດຖະກອນທີ່ອອກໃນຮູບການຕ່າງໆ', 'stat-resign', NULL, 'ຈຳນວນລັດຖະກອນທີ່ອອກໃນຮູບການຕ່າງໆ', 0, NULL, 1, NULL, '2017-09-25 20:15:59', 6, 'stat_resign', NULL),
			(472, 'ຕາຕະລາງສັງລວມ ພະນັກງານຕາມສັນຍາ', 'stat-contract', NULL, 'ຕາຕະລາງສັງລວມ ພະນັກງານຕາມສັນຍາ', 0, NULL, 1, NULL, '2017-09-25 20:16:26', 7, 'stat_contract', NULL),
			(473, 'ຕາຕະລາງບັນຊີໂຄງການຊ່ວຍເຫຼືອທາງການເພື່ອການພັດທະນາ', 'stat-oda', NULL, 'ຕາຕະລາງບັນຊີໂຄງການຊ່ວຍເຫຼືອທາງການເພື່ອການພັດທະນາ', 0, NULL, 106, NULL, '2017-09-25 20:17:01', 8, 'stat_oda', NULL),
			(475, 'ຕາຕະລາງຈຳນວນລັດຖະກອນ ແຍກຕາມຊົນເຜົ່າ', 'stat-officer-ethnic', NULL, 'ຕາຕະລາງຈຳນວນລັດຖະກອນ ແຍກຕາມຊົນເຜົ່າ', 0, NULL, 1, NULL, '2017-09-25 20:17:01', 9, 'stat_officer_ethnic', NULL),
			(476, 'ຊົນເຜົ່າ', 'ethnic', 'fa fa-circle-o', 'ຊົນເຜົ່າ', 0, 1, 443, 1, '2017-09-19 09:27:34', 3, 'ethnic', NULL),
			(477, 'ແຂວງ', 'province', 'fa fa-circle-o', 'ແຂວງ', 0, 1, 443, 1, '2017-09-19 09:27:34', 2, 'province', NULL),
			(478, 'ຜູ້ອະນຸມັດ ມູນນິທິ', 'approver', 'fa fa-circle-o', 'ຜູ້ອະນຸມັດ ມູນນິທິ', 0, 1, 443, 1, '2017-09-19 09:27:34', 4, 'approver', NULL),
			(479, 'ຍ້ອງຍໍຜົນງານ', 'award', 'fa fa-circle-o', 'ຍ້ອງຍໍຜົນງານ', 0, 1, 443, 1, '2017-09-19 09:27:34', 5, 'award', NULL),
			(480, ' ເອກະສານປະເພດປຶ້ມ', 'book', 'fa fa-circle-o', ' ເອກະສານປະເພດປຶ້ມ', 0, 1, 443, 1, '2017-09-19 09:27:34', 7, 'book', NULL),
			(481, 'ປະເພດນິຕິກຳ', 'legal-type', 'fa fa-circle-o', 'ປະເພດນິຕິກຳ', 0, 1, 443, 1, '2017-09-19 09:27:34', 8, 'legal_type', NULL),
			(482, 'ນິຕິກຳ', 'legal', 'fa fa-circle-o', 'ນິຕິກຳ', 0, 1, 443, 1, '2017-09-19 09:27:34', 9, 'legal', NULL);
						
			
		
				
INSERT INTO `moha`.`source_message` (`id`, `category`, `message`)
VALUES
	(1, 'app', 'Branch Groups'),
	(2, 'app', 'Create Branch Group'),
	(3, 'app', 'ID'),
	(4, 'app', 'Name'),
	(5, 'app', 'Deleted'),
	(6, 'app', 'Language'),
	(7, 'app', 'Translation'),
	(8, 'app', 'Messages'),
	(9, 'app', 'Create Message'),
	(10, 'app', 'Create'),
	(11, 'app', 'Update {modelClass}: '),
	(12, 'app', 'Update'),
	(13, 'app', 'Message'),
	(14, 'app', 'Action'),
	(15, 'app', 'Incorrect Requested Params'),
	(16, 'app', 'Cancel'),
	(17, 'app', 'Add'),
	(18, 'app', 'Success'),
	(19, 'app', 'Error'),
	(20, 'app', 'Operation Successful'),
	(21, 'app', 'test'),
	(22, 'app', 'tetas'),
	(23, 'app', 'sdaf'),
	(24, 'app', 'sfadfsdf'),
	(25, 'app', 'xxx'),
	(26, 'app', 'cc'),
	(27, 'app', 'adasd'),
	(28, 'app', 'ee'),
	(29, 'app', 'eedd'),
	(30, 'app', 'gg'),
	(32, 'app', 'pp'),
	(33, 'app', 'Branches'),
	(34, 'app', 'Create Branch'),
	(35, 'app', 'Code'),
	(36, 'app', 'Address'),
	(37, 'app', 'Tel'),
	(38, 'app', 'Branch Group ID'),
	(39, 'app', 'Goverment Unit'),
	(40, 'app', 'Phiscal Years'),
	(41, 'app', 'Create Phiscal Year'),
	(42, 'app', 'Year'),
	(43, 'app', 'Start Date'),
	(44, 'app', 'End Date'),
	(45, 'app', 'Status'),
	(46, 'app', 'Closed'),
	(47, 'app', 'Opening'),
	(48, 'app', 'Delete'),
	(49, 'app', 'Are you sure you want to delete this item?'),
	(50, 'app', 'Operation Success'),
	(51, 'app', 'Date'),
	(52, 'app', 'Phiscal Year'),
	(53, 'app', 'Administration'),
	(54, 'app', 'Dashboard'),
	(55, 'app', 'Ministry'),
	(56, 'app', 'Ministry Group'),
	(57, 'app', 'Goverment Level'),
	(58, 'app', 'Govermentlevels'),
	(59, 'app', 'Create Govermentlevel'),
	(60, 'app', 'New'),
	(61, 'app', 'Save'),
	(62, 'app', 'List'),
	(63, 'app', 'New/Update'),
	(64, 'app', 'Select'),
	(65, 'app', 'Total'),
	(66, 'app', 'Rows'),
	(67, 'app', 'Row(s)'),
	(68, 'app', 'New/Save'),
	(69, 'app', 'Successful'),
	(70, 'app', 'NO'),
	(71, 'app', 'YES'),
	(72, 'app', 'USERNAME'),
	(73, 'app', 'PASSWORD'),
	(74, 'app', 'Branch ID'),
	(75, 'app', 'Effective Date'),
	(76, 'app', 'User ID'),
	(77, 'app', 'Last Update'),
	(78, 'app', 'Phiscal Year ID'),
	(79, 'app', 'Statistics'),
	(80, 'app', 'Goverment Units'),
	(81, 'app', 'No.'),
	(82, 'app', 'Remark'),
	(83, 'app', 'Statistics of Goverment Unit '),
	(84, 'app', 'Select Phiscal Year'),
	(85, 'app', 'Incorrect Phiscal Year'),
	(86, 'app', 'Go Back'),
	(87, 'app', 'Owner'),
	(88, 'app', 'Operation Successfule'),
	(89, 'app', 'Saved'),
	(90, 'app', 'Goverment Level ID'),
	(91, 'app', 'Value'),
	(92, 'app', 'Stat Goverment Unit ID'),
	(93, 'app', 'No Data'),
	(101, 'app', 'Group'),
	(102, 'app', 'Department'),
	(103, 'app', 'Insitute'),
	(104, 'app', 'Center'),
	(105, 'app', 'Institute'),
	(106, 'app', 'Create Stat Goverment Unit'),
	(107, 'app', 'Stat Goverment Units'),
	(108, 'app', 'Stat Goverment Unit'),
	(109, 'app', '-'),
	(110, 'app', 'Office'),
	(111, 'app', 'Position'),
	(112, 'app', 'Stat Single Gateway Implementations'),
	(113, 'app', 'Statistics of Single Gateway Implementations'),
	(114, 'app', 'Service Unit Name'),
	(115, 'app', 'Statistics of Goverment Structure'),
	(116, 'app', 'Ministries'),
	(117, 'app', 'Single Gateway Implementations'),
	(118, 'app', 'Legals'),
	(119, 'app', 'Legal Type'),
	(120, 'app', 'Legal'),
	(121, 'app', 'The Year is not allowed to input'),
	(122, 'app', 'Improve'),
	(123, 'app', 'Publish'),
	(124, 'app', 'Statistics of Internal Legal'),
	(125, 'app', 'Legal Types'),
	(126, 'app', 'Create Legal Type'),
	(127, 'app', 'Create Legal'),
	(128, 'app', 'Legal Type ID'),
	(131, 'app', 'Dashboad'),
	(132, 'app', 'Level'),
	(133, 'app', 'Ministry ID'),
	(134, 'app', 'Province ID'),
	(135, 'app', 'Approver Level ID'),
	(136, 'app', 'Approver Level'),
	(137, 'app', 'approver'),
	(138, 'app', 'Approvers'),
	(139, 'app', 'Create Approver'),
	(140, 'app', 'Approver Levels'),
	(141, 'app', 'Create Approver Level'),
	(142, 'app', 'Province'),
	(143, 'app', 'Stat Association Foundation'),
	(144, 'app', 'Settings'),
	(145, 'app', 'Stat Association Foundations'),
	(146, 'app', 'Statistics of Associations/Foundations'),
	(147, 'app', 'Association'),
	(148, 'app', 'Foundation'),
	(149, 'app', 'Accociations'),
	(150, 'app', 'Foundations'),
	(151, 'app', 'Stat Local Administration'),
	(152, 'app', 'Stat Local Admins'),
	(153, 'app', 'Province Head'),
	(154, 'app', 'Province Vice'),
	(155, 'app', 'District Head'),
	(156, 'app', 'District Vice'),
	(157, 'app', 'T'),
	(158, 'app', 'W'),
	(159, 'app', 'Village Head'),
	(160, 'app', 'Village Vice'),
	(161, 'app', 'Population'),
	(162, 'app', 'Village'),
	(163, 'app', 'Family'),
	(164, 'app', 'P'),
	(165, 'app', 'Statistics of Local Administration'),
	(166, 'app', 'Association Foundation'),
	(167, 'app', 'Local Administration'),
	(168, 'app', 'Religion Teacher'),
	(169, 'app', 'Population Movement'),
	(170, 'app', 'Stat Population Movements'),
	(171, 'app', 'District'),
	(172, 'app', 'Born'),
	(173, 'app', 'Die'),
	(174, 'app', 'Married'),
	(175, 'app', 'Divorced'),
	(176, 'app', 'Move-In'),
	(177, 'app', 'Move-out'),
	(178, 'app', 'Real'),
	(179, 'app', 'Statistics of Population Movement'),
	(180, 'app', 'Stat Religion Teachers'),
	(181, 'app', 'Buddhism'),
	(182, 'app', 'Monk'),
	(183, 'app', 'Novice'),
	(184, 'app', 'Buddhis Dad'),
	(185, 'app', 'Buddhis Mom'),
	(186, 'app', 'Buddhis Boy'),
	(187, 'app', 'Christian'),
	(188, 'app', 'Bahaiy'),
	(189, 'app', 'Idslam'),
	(190, 'app', 'News'),
	(191, 'app', 'Saturday'),
	(192, 'app', 'Catolic'),
	(193, 'app', 'Statistics of Religion Teacher'),
	(194, 'app', 'Comparations of Population Movement'),
	(195, 'app', 'Inquiry'),
	(196, 'app', 'Women'),
	(197, 'app', 'The Chart of Population Movement Yearly'),
	(198, 'app', 'Ethnic Statistic'),
	(199, 'app', 'Ethic'),
	(200, 'app', 'Stat Ethnics'),
	(201, 'app', 'Enthnic'),
	(202, 'app', 'Search'),
	(203, 'app', 'Statistics of Ehtnics'),
	(204, 'app', 'Ethnics'),
	(205, 'app', 'Create Ethnic'),
	(206, 'app', 'Ethnic'),
	(207, 'app', 'Incorrect Request Method'),
	(208, 'app', 'Religion & Other Believes'),
	(209, 'app', 'Statistics of Religions & Other Believes'),
	(210, 'app', 'Others'),
	(211, 'app', 'Other'),
	(212, 'app', 'The Chart of Religions & Other Believes'),
	(213, 'app', 'Christ'),
	(214, 'app', 'The Chart of Religions Teacher'),
	(215, 'app', 'Religion Place'),
	(216, 'app', 'Stat Religion Places'),
	(217, 'app', 'Temple'),
	(218, 'app', 'No Monk'),
	(219, 'app', 'Sim'),
	(220, 'app', 'No Sim'),
	(221, 'app', 'Not'),
	(222, 'app', 'N'),
	(223, 'app', 'The Chart of Religions Places'),
	(224, 'app', 'Statistics of Religion Place'),
	(225, 'app', 'Bahai'),
	(226, 'app', 'Officer'),
	(227, 'app', 'Overall Officer'),
	(228, 'app', 'Stat Officers'),
	(229, 'app', 'Create Stat Officer'),
	(230, 'app', 'Statistics of Officers'),
	(231, 'app', 'Overall Officers'),
	(232, 'app', 'Description'),
	(233, 'app', 'No. of officers'),
	(234, 'app', 'Men'),
	(235, 'app', 'Ministry Level'),
	(236, 'app', 'Local Level'),
	(237, 'app', 'Province Department'),
	(238, 'app', 'District Office'),
	(239, 'app', 'Officers By Ages'),
	(240, 'app', 'Stat Officer Ages'),
	(241, 'app', 'Statistics of Officers By Ages'),
	(242, 'app', 'Officers By Degrees'),
	(243, 'app', 'Stat Officer Degrees'),
	(244, 'app', 'Doctor'),
	(245, 'app', 'Post Master'),
	(246, 'app', 'Master'),
	(247, 'app', 'Post Bachelor'),
	(248, 'app', 'Bachelor'),
	(249, 'app', 'High'),
	(250, 'app', 'Middle'),
	(251, 'app', 'Begin'),
	(252, 'app', 'No Degree'),
	(253, 'app', 'Retire'),
	(254, 'app', 'Bumnet'),
	(255, 'app', 'Leave'),
	(256, 'app', 'Fire'),
	(257, 'app', 'Resign'),
	(258, 'app', 'Lose'),
	(259, 'app', 'Move to SOE'),
	(260, 'app', 'Moveto Ministry'),
	(261, 'app', 'Move-In Ministry'),
	(262, 'app', 'Officers Resignation'),
	(263, 'app', 'Stat Officer Resigns'),
	(264, 'app', 'Officers Add'),
	(265, 'app', 'Stat Officer Adds'),
	(266, 'app', 'Create Stat Officer Add'),
	(267, 'app', 'Statistics of Officers Addition'),
	(268, 'app', 'By Quota'),
	(269, 'app', 'From Army'),
	(270, 'app', 'From SOE'),
	(271, 'app', 'Officers Addition'),
	(272, 'app', 'Officers Contract'),
	(273, 'app', 'Stat Officer Contracts'),
	(274, 'app', 'Admin Approve'),
	(275, 'app', 'Admin Non Approve'),
	(276, 'app', 'Officer Approve'),
	(277, 'app', 'Officer Non Approve'),
	(278, 'app', 'Administration By Contract'),
	(279, 'app', 'Officers By Contract'),
	(280, 'app', 'Officers Approve'),
	(281, 'app', 'Officers Non Approve'),
	(282, 'app', 'Officers Positions'),
	(283, 'app', 'Stat Officer Positions'),
	(284, 'app', 'Statistics of Officers By Positions'),
	(285, 'app', 'Statistics Officer Positions'),
	(286, 'app', 'Officers Needed'),
	(287, 'app', 'Stat Officer Needs'),
	(288, 'app', 'Needed Plan'),
	(289, 'app', 'Officers Ministry'),
	(290, 'app', 'Stat Officer Ministries'),
	(293, 'app', 'Organisation'),
	(294, 'app', 'Organisations'),
	(295, 'app', 'Create Organisation'),
	(296, 'app', 'Officers Organisation'),
	(297, 'app', 'Stat Officer Organisations'),
	(298, 'app', 'Officers Province'),
	(299, 'app', 'Stat Officer Provinces'),
	(300, 'app', 'Officers Ministry Add'),
	(301, 'app', 'Stat Officer Ministries Add/Resign'),
	(302, 'app', 'Officers Organisation Add'),
	(303, 'app', 'Stat Officer Organisations Add/Resign'),
	(308, 'app', 'Officers Province Add'),
	(309, 'app', 'Stat Officer Province Adds'),
	(310, 'app', 'Create Stat Officer Province Add'),
	(311, 'app', 'Stat Officer Provinces Add/Resign'),
	(312, 'app', 'Officers Ministry Train'),
	(313, 'app', 'Technical Trainning'),
	(314, 'app', 'Theory Trainning'),
	(315, 'app', 'Local'),
	(316, 'app', 'Oversea'),
	(317, 'app', 'Stat Officer Province Trains'),
	(318, 'app', 'Create Stat Officer Province Train'),
	(319, 'app', 'Add/Resign'),
	(320, 'app', 'Training'),
	(321, 'app', 'Officers Province Train'),
	(322, 'app', 'Statistics of Tranining of Ministry Officers '),
	(330, 'app', 'Officers Organisation Train'),
	(331, 'app', 'Stat Officer Org Trains'),
	(332, 'app', 'Create Stat Officer Org Train'),
	(333, 'app', 'Statistics of Tranining of Province Officers '),
	(334, 'app', 'Upgrade'),
	(335, 'app', 'Officers Ministry Upgrade'),
	(336, 'app', 'Officers Organisation Upgrade'),
	(337, 'app', 'Officers Province Upgrade'),
	(338, 'app', 'Statistics of Tranining of Organisation Officers '),
	(339, 'app', 'Stat Officer Province Upgrades'),
	(340, 'app', 'Create Stat Officer Province Upgrade'),
	(341, 'app', 'Stat Officer Provinces Traning'),
	(342, 'app', 'Stat Officer Provinces Upgrade'),
	(343, 'app', 'Statistics of Upgrading of Province Officers '),
	(344, 'app', 'The Chart of Officers Province Training'),
	(345, 'app', 'Organisation Officer Upgrading'),
	(346, 'app', 'Doctor Local'),
	(347, 'app', 'Doctor Oversea'),
	(348, 'app', 'Master Local'),
	(349, 'app', 'Master Oversea'),
	(350, 'app', 'Bachelor Local'),
	(351, 'app', 'Bachelor Oversea'),
	(352, 'app', 'High Local'),
	(353, 'app', 'High Oversea'),
	(354, 'app', 'Middle Local'),
	(355, 'app', 'Middle Oversea'),
	(356, 'app', 'Begin Local'),
	(357, 'app', 'Begin Oversea'),
	(358, 'app', 'Stat Course ID'),
	(359, 'app', 'Course'),
	(360, 'app', 'Stat Courses'),
	(361, 'app', 'Create Stat Course'),
	(362, 'app', 'Statistics of Officer Training Course Development'),
	(363, 'app', 'Parent'),
	(364, 'app', 'Table of statistic of officer training course'),
	(365, 'app', 'Insitutution Training'),
	(366, 'app', 'Stat Institute Trains'),
	(367, 'app', 'Title'),
	(368, 'app', 'Cooperator'),
	(369, 'app', 'Times'),
	(370, 'app', 'Place'),
	(371, 'app', 'Statistics of Institution Training'),
	(372, 'app', 'Attendance'),
	(374, 'app', 'Insitutution Meeting'),
	(375, 'app', 'Stat Institute Meetings'),
	(376, 'app', 'Create Stat Institute Meeting'),
	(377, 'app', 'Statistics of Institution Meeting'),
	(378, 'app', 'The Chart of Officers Organisation Training'),
	(379, 'app', 'Technical Local'),
	(380, 'app', 'Technical Oversea'),
	(381, 'app', 'Theory Local'),
	(382, 'app', 'Theory Oversea'),
	(383, 'app', 'Ministry Officer Upgrading'),
	(384, 'app', 'Research'),
	(385, 'app', 'Stat Researches'),
	(386, 'app', 'Create Stat Research'),
	(387, 'app', 'Stat Researchs'),
	(388, 'app', 'Goverment'),
	(389, 'app', 'Dornor'),
	(390, 'app', 'Scholarship'),
	(391, 'app', 'Attendee'),
	(392, 'app', 'Statistics of Research'),
	(393, 'app', ''),
	(394, 'app', 'Performance'),
	(395, 'app', 'Stat Highcoin Ministries'),
	(396, 'app', 'Create Stat Highcoin Ministry'),
	(398, 'app', 'Awards'),
	(399, 'app', 'Create Award'),
	(400, 'app', 'Award'),
	(437, 'app', 'Statistics of Highcoin Ministry'),
	(438, 'app', 'Stat Hornorcoin Provinces'),
	(439, 'app', 'Create Stat Hornorcoin Province'),
	(440, 'app', 'Stat Hornorcoin Ministries'),
	(441, 'app', 'Statistics of Hornor Coin Province'),
	(442, 'app', 'Stat Victorycoin Ministries'),
	(443, 'app', 'Stat Victorycoin Provinces'),
	(444, 'app', 'Statistics of Highcoin Province'),
	(445, 'app', 'Stat Govcoin Ministries'),
	(446, 'app', 'Create Stat Govcoin Ministry'),
	(447, 'app', 'Stat Goverment Coin Ministries'),
	(448, 'app', 'Stat Victoryoversea Ministries'),
	(477, 'app', 'Stat Victoryoversea Provinces'),
	(478, 'app', 'Create Stat Victoryoversea Province'),
	(479, 'app', 'Stat Goverment Oversea Ministries'),
	(480, 'app', 'Statistics of Govoversea Ministry'),
	(481, 'app', 'Stat Govcoin Provinces'),
	(482, 'app', 'Create Stat Govcoin Province'),
	(483, 'app', 'Stat Goverment Coin Provinces'),
	(484, 'app', 'Statistics of GovCoin Province'),
	(485, 'app', 'Stat Goverment Oversea Provinces'),
	(486, 'app', 'Statistics of GovOversea Province'),
	(487, 'app', 'Document'),
	(488, 'app', 'Stat Documents'),
	(489, 'app', 'Create Stat Document'),
	(490, 'app', 'Section'),
	(491, 'app', 'Book Type'),
	(492, 'app', 'Books'),
	(493, 'app', 'Create Book'),
	(500, 'app', 'Bad Request'),
	(501, 'app', 'Stat Copies'),
	(502, 'app', 'Activity'),
	(503, 'app', 'ໄລຍະເວລາຈັດຕັ້ງປະຕິບັດ'),
	(504, 'app', 'Summary'),
	(505, 'app', 'Stat Map Services'),
	(506, 'app', 'Statistics of Map Service'),
	(507, 'app', 'Stat Map Produces'),
	(508, 'app', 'Stat Explores'),
	(514, 'app', 'Officer Levels'),
	(515, 'app', 'Create Officer Level'),
	(516, 'app', 'Stat Officer Salaries'),
	(517, 'app', 'Statistics of Officers by Salary Level'),
	(518, 'app', 'Stat Officer Age Levels'),
	(519, 'app', 'Create Stat Officer Age Level'),
	(520, 'app', 'Statistics of Officers by Degree'),
	(521, 'app', 'Stat Officer Ministries Upgrade'),
	(522, 'app', 'The Chart of Officers Ministry Training'),
	(523, 'app', 'ກົມພັດທະນາການບໍລິຫານລັດ'),
	(524, 'app', 'ສະຖິຕິກົງຈັກຂອງລັດຖະບານ.... ກະຊວງ ..... ອົງກາ'),
	(525, 'app', 'ລາຍງານ'),
	(526, 'app', 'ປ້ອນຂໍ້ມູນ'),
	(527, 'app', 'ສະຖິຕິບັນດາຫົວໜ່ວຍການຈັດຕັ້ງ (ກົມ, ສະຖາບັນ, ສ'),
	(528, 'app', 'ສະຖິຕິບັນດານິຕິກຳຂະແໜງພາຍໃນທີ່ກຳລັງປັບປຸງ ແລະ'),
	(529, 'app', 'ສະຖິຕິໜ່ວຍງານຈັດຕັ້ງປະຕິບັດກົນໄກການບໍລິການຜ່າ'),
	(530, 'app', 'ສະຖິຕິສະມາຄົມ/ມູນນິທິໃນທົ່ວປະເທດ'),
	(531, 'app', 'ຮ່າງໂຄງປະກອບກົງຈັກການຈັດຕັ້ງ ແລະ ບຸກຄະລະກອນຂອ'),
	(532, 'app', 'ກົມການປົກຄອງທ້ອງຖິ່ນ'),
	(533, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕໍາແໜ່ງເຈົ້າແຂວງ, ຮອງເຈົ້າແຂວງ,'),
	(534, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງຫົວໜ້າ ແລະ ຮອງຫົວໜ້າຫ້ອງວ'),
	(535, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງຫົວໜ້າ, ຮອງຫົວໜ້າພະແນກ ແລ'),
	(536, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນກ່ຽວກັບເມືອງ, ບ້ານ ທົ່ວແຂວ'),
	(537, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງເຈົ້າເມືອງ ແລະ ຮອງເຈົ້າເມ'),
	(538, 'app', 'ລາຍຊື່ຜູ້ລົງຕຳແໜ່ງຫົວໜ້າ ແລະ ຮອງຫົວໜ້າຫ້ອງວ່າ'),
	(539, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງຫົວໜ້າຫ້ອງການ, ຮອງຫົວໜ້າຫ'),
	(540, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນກ່ຽວກັບເມືອງ ໃນເຂດຕົວເມືອງ'),
	(541, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນກ່ຽວກັບເມືອງ ໃນເຂດຊົນນະບົດ'),
	(542, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນບ້ານເປົ້າໝາຍເຮັດບ້ານສາມສ້າ'),
	(543, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນຂັ້ນບ້ານ'),
	(544, 'app', 'ກົມວຽກງານຊົນເຜົ່າ ແລະ ສາສະໜາ'),
	(545, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິປະຊາຊົນເຊື່ອຖືສາສະໜາ ແລະ ຄ'),
	(546, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິະສົງ, ສາມະເນນ, ຄູຄຳສອນ ແລະ'),
	(547, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິສາສະນະສະຖານໃນທົ່ວປະເທດ'),
	(548, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິຊົນເຜົ່າໃນທົ່ວແຂວງ'),
	(549, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິຊົນເຜົ່າໃນທົ່ວເມືອງ'),
	(550, 'app', 'ກົມຄຸ້ມຄອງພົນລະເມືອງ'),
	(551, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງລາວທົ່ວປະເທດ'),
	(552, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງຂອງແຂວງ...... ປະ'),
	(553, 'app', 'ຕາຕະລາງບັນທຶກສະຖິຕິພົນລະເມືອງຂອງແຂວງ....... ປ'),
	(554, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງ'),
	(555, 'app', 'ຕາຕະລາງບັນທຶກສະຖິຕິພົນລະເມືອງຂອງເມືອງປະຈຳ 6 ເ'),
	(556, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງຂອງບ້ານປະຈຳງວດ..'),
	(557, 'app', 'ຕາຕະລາງບັນທຶກການເກີດຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳ'),
	(558, 'app', 'ຕາຕະລາງບັນທຶກການແຕ່ງດອງຂອງພົນລະເມືອງຂອງບ້ານ ປ'),
	(559, 'app', 'ຕາຕະລາງບັນທຶກການຢ່າຮ້າງຂອງພົນລະເມືອງຂອງບ້ານ ປ'),
	(560, 'app', 'ຕາຕະລາງບັນທຶກການຍົກຍ້າຍມາຂອງພົນລະເມືອງຂອງບ້ານ'),
	(561, 'app', 'ຕາຕະລາງບັນທຶກສາເຫດການຍົກຍ້າຍໄປຂອງພົນລະເມືອງຂອ'),
	(562, 'app', 'ຕາຕະລາງບັນທຶກສາເຫດານເສຍຊີວິດຂອງພົນລະເມືອງຂອງບ'),
	(563, 'app', 'ກົມຄຸ້ມຄອງລັດຖະກອນ'),
	(564, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນພະນັກງານ ແຍກຕາມຊັ້ນ-ຂັ້ນເງິ'),
	(565, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນ-ຂັ້ນເງິນ'),
	(566, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມວິຊາສະເພາະ'),
	(567, 'app', 'ຕາຕະລາງສັງລວມລັດຖະກອນແຍກຕາມເກນອາຍຸ'),
	(568, 'app', 'ຕາຕະລາງສັງລວມລັດຖະກອນແຍກຕາມຊົນເຜົ່າ'),
	(569, 'app', 'ຕາຕະລາງສັງລວມລັດຖະກອນແຍກຕາມຕຳແໜ່ງບໍລິຫານ'),
	(570, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ເຂົ້າເພີ່ມໃນຮູບກ'),
	(571, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ອອກພີ່ມໃນຮູບການຕ'),
	(572, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນພະນັກງານຕາມສັນຍາ'),
	(573, 'app', 'ຕາຕະລາງຈຳນວນລັດຖະກອນທີ່ມີເງື່ອນໄຂຮັບບຳນານ'),
	(574, 'app', 'ກົມປະເມີນຜົນ ແລະ ພັດທະນາລັດຖະກອນ'),
	(575, 'app', 'ຕາຕະລາງລາຍງານສະຖິຕິພະນັກງານ-ລັດຖະກອນຂັ້ນກະຊວງ'),
	(576, 'app', 'ຕາຕະລາງສະຖິຕິພະນັກງານ-ລັດຖະກອນຂັ້ນກະຊວງ-ອົງກາ'),
	(577, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຍົກລະດັບວິຊາສະ'),
	(578, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມຢູ່ພາ'),
	(579, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມຢູ່ຕ່'),
	(580, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນໄປຝຶກອົບຮ'),
	(581, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມທິດສະ'),
	(582, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນທີ່ໄປຍົກລ'),
	(583, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິລັດຖະກອນໄປຝຶກອົບຮົມວິຊາສະເ'),
	(584, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມວິຊາສ'),
	(585, 'app', 'ສະຖາບັນຄົ້ນຄວ້າວິທະຍາສາດການປົກຄອງ ແລະ ຝຶກອົບຮ'),
	(586, 'app', 'ຕາຕະລາງສະຖິຕິສັງລວມການສ້າງ ແລະ ພັດທະນາຫຼັກສູດ'),
	(587, 'app', 'ຕາຕະລາງສະຖິຕິການສະໜອງຫຼັກສູດໃຫ້ບັນດາພາກສ່ວນສູ'),
	(588, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິການເຂົ້າຮ່ວມຊ່ວຍເປັນວິທະຍາ'),
	(589, 'app', 'ຕາຕະລາງສະຖິຕິສັງລວມການຈັດກອງປະຊຸມ-ຝຶກອົບຮົມໃຫ'),
	(590, 'app', 'ສັງລວມສະຖິຕິສູນຄົ້ນຄວ້າວຽກງານການປົກຄອງ'),
	(591, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິການເຂົ້ານຳໃຊ້ປຶ້ມຕຳລາຫໍສະໝ'),
	(592, 'app', 'ຕາຕະລາງສະຖິຕິສັງລວມການເຂົ້າຮ່ວມຝຶກອົບຮົມຂອງພະ'),
	(593, 'app', 'ກົມສຳເນົາເອກະສານແຫ່ງຊາດ'),
	(594, 'app', 'ສະຖິຕິການທ້ອນໂຮມເອກະສານທີ່ມີຄວາມສຳຄັນແຫ່ງຊາດ'),
	(595, 'app', 'ກົມແຂ່ງຂັນ ແລະ ຍ້ອງຍໍ'),
	(596, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສໍາລັບຍ້ອງຍໍພາຍໃນກະຊວງ, ອົ'),
	(597, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສໍາລັບຍ້ອງຍໍພາຍໃນກະຊວ'),
	(598, 'app', 'ຕາຕະລາງປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອ'),
	(599, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັ'),
	(600, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂ'),
	(601, 'app', 'ຕາຕະລາງປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍສາກົນຂອ'),
	(602, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍສາກົນຂອງບັ'),
	(603, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍສາກົນ ຂອງບ'),
	(604, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສຳລັບຍ້ອງຍໍສາກົນຂອງບັນດາກະ'),
	(605, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສຳລັບຍ້ອງຍໍສາກົນຂອງບັນດາແຂ'),
	(606, 'app', 'ກົມແຜນທີ່ແຫ່ງຊາດ'),
	(607, 'app', 'ສະຖິຕິການເຄື່ອນໄຫວວຽກງານສຳຫຼວດປະຈຳປີ ......'),
	(608, 'app', 'ສະຖິຕິການບໍລິການແຜນທີ່ມາດຕາສ່ວນ'),
	(609, 'app', 'ສະຖິຕິການຜະລິດແຜນທີ່'),
	(610, 'app', 'ສູນສຳຫຼວດວັດແທກ ແລະ ແຜນທີ່'),
	(611, 'app', 'ສະຖິຕິການສຳຫຼວດວັດແທກ ແລະ ວຽກງານການພິມ'),
	(612, 'app', 'ຫ້ອງການກະຊວງ'),
	(613, 'app', 'ກົມແຜນການ ແລະ ການຮ່ວມມື'),
	(614, 'app', 'ຕາຕະລາງບັນຊີໂຄງການຊ່ວຍເຫຼືອທາງການເພື່ອການພັດທ'),
	(615, 'app', 'ຕາຕະລາງສະຖິຕິການຮ່ວມມື'),
	(616, 'app', 'ກົມຈັດຕັ້ງ ແລະ ພະນັກງານ'),
	(617, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນສຳລັບຊັ້ນ .... ເຖິງ'),
	(618, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນວິຊາສະເພາ'),
	(619, 'app', 'ຕາຕະລາງ ຈຳນວນລັດຖະກອນແຍກຕາມເກນອາຍຸ'),
	(620, 'app', 'ຕາຕະລາງ ຈຳນວນລັດຖະກອນແຍກຕາມຊົນເຜົ່າ'),
	(621, 'app', 'ຕາຕະລາງສັງລວມລັດຖະກອນຜູ້ທີ່ໄດ້ຮັບຕໍາແໜ່ງບໍລິຫ'),
	(622, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ເພີ່ມເຂົ້າໃນຮູບກ'),
	(623, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ອອກໃນຮູບການຕ່າງໆ'),
	(624, 'app', 'ຈໍານວນລັດຖະກອນທີ່ມີເງື່ອນໄຂຮັບບຳນານ'),
	(625, 'app', 'ຕາຕະລາງສັງລວມຊີວະປະຫວັດຫຍໍ້ຂອງພະນັກງານ'),
	(626, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນພະນັກງານ (ສະເພາະຊັ້ນ VI) ແຍ'),
	(627, 'app', 'ກົມກວດກາ'),
	(628, 'app', 'ຜູ້ໃຊ້ລະບົບ'),
	(629, 'app', 'ສິດແລະບົດບາດ'),
	(630, 'app', 'ຕັ້ງຄ່າ'),
	(631, 'app', 'Roles'),
	(632, 'app', 'Create Role'),
	(633, 'app', 'Input Dt Stamp'),
	(634, 'app', 'ສະຖິຕິບັນດາຫົວໜ່ວຍການຈັດຕັ້ງ (ກົມ, ສະຖາບັນ, ສູນ ແລະ ທຽບເທົ່າກົມ)'),
	(635, 'app', 'ສະຖິຕິໜ່ວຍງານຈັດຕັ້ງປະຕິບັດກົນໄກການບໍລິການຜ່ານປະຕູດຽວ'),
	(636, 'app', 'ສະຖິຕິກົງຈັກຂອງລັດຖະບານ.... ກະຊວງ ..... ອົງການລັດທຽບເທົ່າ'),
	(637, 'app', 'ສະຖິຕິບັນດານິຕິກຳຂະແໜງພາຍໃນທີ່ກຳລັງປັບປຸງ ແລະ ຮ່າງຂຶ້ນໃໝ່'),
	(638, 'app', 'ຮ່າງໂຄງປະກອບກົງຈັກການຈັດຕັ້ງ ແລະ ບຸກຄະລະກອນຂອງກະຊວງ/ອົງການລັດທຽບເທົ່າກະຊວງ'),
	(639, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕໍາແໜ່ງເຈົ້າແຂວງ, ຮອງເຈົ້າແຂວງ, ເຈົ້າຄອງນະຄອນ ແລະ ຮອງເຈົ້າຄອງນະຄອນ'),
	(640, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງຫົວໜ້າ ແລະ ຮອງຫົວໜ້າຫ້ອງວ່າການປົກຄອງແຂວງ'),
	(641, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງຫົວໜ້າ, ຮອງຫົວໜ້າພະແນກ ແລະ ອົງການທຽບເທົ່າ'),
	(642, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນກ່ຽວກັບເມືອງ, ບ້ານ ທົ່ວແຂວງ'),
	(643, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງເຈົ້າເມືອງ ແລະ ຮອງເຈົ້າເມືອງ'),
	(644, 'app', 'ລາຍຊື່ຜູ້ລົງຕຳແໜ່ງຫົວໜ້າ ແລະ ຮອງຫົວໜ້າຫ້ອງວ່າການປົຄອງເມືອງ'),
	(645, 'app', 'ລາຍຊື່ຜູ້ດຳລົງຕຳແໜ່ງຫົວໜ້າຫ້ອງການ, ຮອງຫົວໜ້າຫ້ອງການ ແລະ ອົງການທຽບເທົ່າ'),
	(646, 'app', 'ຕາຕະລາງສັງລວມຂໍ້ມູນບ້ານເປົ້າໝາຍເຮັດບ້ານສາມສ້າງ'),
	(647, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິປະຊາຊົນເຊື່ອຖືສາສະໜາ ແລະ ຄວາມເຊື່ອໃນທົ່ວປະເທດ'),
	(648, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິະສົງ, ສາມະເນນ, ຄູຄຳສອນ ແລະ ຄະນະຮັບຜິດຊອບສາສະໜາ'),
	(649, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງຂອງແຂວງ...... ປະຈໍາປີ.......'),
	(650, 'app', 'ຕາຕະລາງບັນທຶກສະຖິຕິພົນລະເມືອງຂອງແຂວງ....... ປະຈຳປີ.......'),
	(651, 'app', 'ຕາຕະລາງບັນທຶກສະຖິຕິພົນລະເມືອງຂອງເມືອງປະຈຳ 6 ເດືອນ....... ປະຈຳປີ ............'),
	(652, 'app', 'ຕາຕະລາງສັງລວມສະຖິຕິພົນລະເມືອງຂອງບ້ານປະຈຳງວດ.......... ປະຈຳປີ .............'),
	(653, 'app', 'ຕາຕະລາງບັນທຶກການເກີດຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳວັນ ປະຈຳປີ .............'),
	(654, 'app', 'ຕາຕະລາງບັນທຶກການແຕ່ງດອງຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳວັນ ປະຈໍາປີ ..........'),
	(655, 'app', 'ຕາຕະລາງບັນທຶກການຢ່າຮ້າງຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳວັນ ປະຈໍາປີ ...........'),
	(656, 'app', 'ຕາຕະລາງບັນທຶກການຍົກຍ້າຍມາຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳວັນ ປະຈຳປີ .......'),
	(657, 'app', 'ຕາຕະລາງບັນທຶກສາເຫດການຍົກຍ້າຍໄປຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳວັນ ປະຈຳປີ .....'),
	(658, 'app', 'ຕາຕະລາງບັນທຶກສາເຫດານເສຍຊີວິດຂອງພົນລະເມືອງຂອງບ້ານ ປະຈຳປີ ...........'),
	(659, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນພະນັກງານ ແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ (ສະເພາະຊັ້ນ VI)'),
	(660, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ (ແຕ່ຊັ້ນ I-V)'),
	(661, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ເຂົ້າເພີ່ມໃນຮູບການຕ່າງໆ'),
	(662, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ອອກພີ່ມໃນຮູບການຕ່າງໆ'),
	(663, 'app', 'ຕາຕະລາງລາຍງານສະຖິຕິພະນັກງານ-ລັດຖະກອນຂັ້ນກະຊວງ-ອົງການທຽບເທົ່າ ແລະ ທ້ອງຖິ່ນໄປຝຶກອົບຮົມຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(664, 'app', 'ຕາຕະລາງສະຖິຕິພະນັກງານ-ລັດຖະກອນຂັ້ນກະຊວງ-ອົງການທຽບເທົ່າ ແລະ ທ້ອງຖິ່ນໄປຍົກລະດັບ (ໄປຮຽນຕໍ່) ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(665, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຍົກລະດັບວິຊາສະເພາະຢູ່ພາຍໃນປະເທດ'),
	(666, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຍົກລະດັບວິຊາສະເພາະຢູ່ຕ່າງປະເທດ'),
	(667, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມຢູ່ພາຍໃນປະເທດ'),
	(668, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມຢູ່ຕ່າງປະເທດ'),
	(669, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນໄປຝຶກອົບຮົມທິດສະດີຢູ່ພາຍໃນປະເທດ'),
	(670, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນໄປຝຶກອົບຮົມທິດສະດີຢູ່ຕ່າງປະເທດ'),
	(671, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມທິດສະດີຢູ່ພາຍໃນປະເທດ'),
	(672, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມທິດສະດີຢູ່ຕ່າງປະເທດ'),
	(673, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນທີ່ໄປຍົກລະດັບວິຊາສະເພາະຢູ່ພາຍໃນປະເທດ (ໄປຮຽນຕໍ່ຊັ້ນໃໝ່)'),
	(674, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນທີ່ໄປຍົກລະດັບວິຊາສະເພາະຢູ່ຕ່າງປະເທດ (ໄປຮຽນຕໍ່ຊັ້ນໃໝ່)'),
	(675, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິລັດຖະກອນໄປຝຶກອົບຮົມວິຊາສະເພາະຢູ່ພາຍໃນປະເທດ'),
	(676, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິລັດຖະກອນໄປຝຶກອົບຮົມວິຊາສະເພາະຢູ່ຕ່າງປະເທດ'),
	(677, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມວິຊາສະເພາະຢູ່ພາຍໃນປະເທດ'),
	(678, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ໄປຝຶກອົບຮົມວິຊາສະເພາະຢູ່ຕ່າງປະເທດ'),
	(679, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນໄປຝຶກອົບຮົມວິຊາສະເພາະຢູ່ພາຍໃນປະເທດ'),
	(680, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິພະນັກງານ-ລັດຖະກອນໄປຝຶກອົບຮົມວິຊາສະເພາະຢູ່ຕ່າງປະເທດ'),
	(681, 'app', 'ສະຖາບັນຄົ້ນຄວ້າວິທະຍາສາດການປົກຄອງ ແລະ ຝຶກອົບຮົມ'),
	(682, 'app', 'ຕາຕະລາງສະຖິຕິການສະໜອງຫຼັກສູດໃຫ້ບັນດາພາກສ່ວນສູນກາງ ແລະ ທ້ອງຖິ່ນ (ຕາມການສະເໜີ)'),
	(683, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິການເຂົ້າຮ່ວມຊ່ວຍເປັນວິທະຍາກອນຕາມການເຊື້ອເຊີນ'),
	(684, 'app', 'ຕາຕະລາງສະຖິຕິສັງລວມການຈັດກອງປະຊຸມ-ຝຶກອົບຮົມໃຫ້ບັນດາກະຊວງ-ອົງການຂັ້ນສູນກາງ ແລະ ທ້ອງຖິ່ນ'),
	(685, 'app', 'ຕາຕະລາງເກັບກຳສະຖິຕິການເຂົ້ານຳໃຊ້ປຶ້ມຕຳລາຫໍສະໝຸດ'),
	(686, 'app', 'ຕາຕະລາງສະຖິຕິສັງລວມການເຂົ້າຮ່ວມຝຶກອົບຮົມຂອງພະນັກງານ-ລັດຖະກອນ ພາຍໃນສະຖາບັນ'),
	(687, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສໍາລັບຍ້ອງຍໍພາຍໃນກະຊວງ, ອົງການ'),
	(688, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສໍາລັບຍ້ອງຍໍພາຍໃນກະຊວງ, ອົງການ'),
	(689, 'app', 'ຕາຕະລາງປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ'),
	(690, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງ'),
	(691, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງ'),
	(692, 'app', 'ຕາຕະລາງປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍສາກົນຂອງບັນດາກະຊວງ, ອົງການ'),
	(693, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍສາກົນຂອງບັນດາກະຊວງ, ອົງການ'),
	(694, 'app', 'ຕາຕະລາງປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍສາກົນ ຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ'),
	(695, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສຳລັບຍ້ອງຍໍສາກົນຂອງບັນດາກະຊວງ, ອົງການ'),
	(696, 'app', 'ຕາຕະລາງປະເພດຫຼຽນກາ ສຳລັບຍ້ອງຍໍສາກົນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ'),
	(697, 'app', 'ຕາຕະລາງບັນຊີໂຄງການຊ່ວຍເຫຼືອທາງການເພື່ອການພັດທະນາ (ODA)'),
	(698, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນສຳລັບຊັ້ນ .... ເຖິງ ..... ແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ'),
	(699, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນວິຊາສະເພາະ'),
	(700, 'app', 'ຕາຕະລາງສັງລວມລັດຖະກອນຜູ້ທີ່ໄດ້ຮັບຕໍາແໜ່ງບໍລິຫານປະເພດຕ່າງໆ'),
	(701, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນທີ່ເພີ່ມເຂົ້າໃນຮູບການຕ່າງໆ'),
	(702, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນພະນັກງານ (ສະເພາະຊັ້ນ VI) ແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ'),
	(703, 'app', 'User Control'),
	(704, 'app', 'Role Name'),
	(705, 'app', 'Created Date Time'),
	(706, 'app', 'New Record'),
	(707, 'app', 'Menu Item(s)'),
	(708, 'app', 'Aaction Item(s)'),
	(709, 'app', 'ກົມພັດທະນາ ແລະ ການບໍລິຫານລັດ'),
	(710, 'app', 'ສະຖິຕິຊົນເຜົ່າໃນທົ່ວປະເທດ'),
	(711, 'app', 'ສະຖິຕິປະຊາຊົນເຊື່ອຖືສາສະໜາ ແລະ ຄວາມເຊື່ອອື່ນໃນທົ່ວປະເທດ '),
	(712, 'app', 'ສະຖິຕິພະສົງ ແລະ ຄູສອນສາສະໜາ ໃນທົ່ວປະເທດ'),
	(713, 'app', 'ສະຖິຕິສາສະນະສະຖານໃນທົ່ວປະເທດ'),
	(714, 'app', 'ການເກັບກຳສະຖິຕິການເໜັງຕີງຂອງພົນລະເມືອງ ຂອງກະຊວງພາຍໃນ ປະຈຳປີ'),
	(715, 'app', 'ການສົມທຽບສະຖິຕິເໜັງຕີງຂອງພົນລະເມືອງຂອງປີ'),
	(716, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນໃນທົ່ວປະເທດ'),
	(717, 'app', 'ຈຳນວນລັດຖະກອນທີ່ອອກໃນຮູບການຕ່າງໆ'),
	(718, 'app', 'ຈຳນວນລັດຖະກອນທີ່ເຂົ້າເພີ່ມໃນຮູບການຕ່າງໆ'),
	(719, 'app', 'ຈຳນວນພະນັກງານຕາມສັນຍາ'),
	(720, 'app', 'ຈຳນວນລັດຖະກອນແຍກຕາມຕຳແໜ່ງບໍລິຫານປະເພດຕ່າງໆ'),
	(721, 'app', 'ແຜນຄວາມຕ້ອງການລັດຖະກອນໃໝ່'),
	(722, 'app', 'ສະຖິຕິລັດຖະກອນລວມຂອງແຕ່ລະກະຊວງ, ອົງການທຽບເທົ່າກະຊວງ'),
	(723, 'app', 'ສະຖິຕິລວມຂອງອົງການຈັດຕັ້ງຂັ້ນສູນກາງ'),
	(724, 'app', 'ຕາຕະລາງສະຖິຕິການພັດທະນາຫຼັກສູດເຝິກອົບຮົມລັດຖະກອນ'),
	(725, 'app', 'ສະຖິຕິການສັງລວມ ການສຳເນົາ'),
	(726, 'app', 'ປະເພດຫຼຽນໄຊຊັ້ນສູງ ແລະ ຫຼຽນນາມມະຍົດຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ'),
	(727, 'app', 'ປະເພດຫຼຽນນາມມະຍົດຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ'),
	(728, 'app', 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບການຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ'),
	(729, 'app', 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ'),
	(730, 'app', 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາກະຊວງ, ອົງການ'),
	(731, 'app', 'ປະເພດຫຼຽນຊັ້ນສູງ ສຳລັບການຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ'),
	(732, 'app', 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ'),
	(733, 'app', 'ປະເພດຫຼຽນໄຊຕ່າງໆ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ'),
	(734, 'app', 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາກະຊວງ, ອົງການ'),
	(735, 'app', 'ປະເພດຫຼຽນກາສຳລັບຍ້ອງຍໍພາຍໃນຂອງບັນດາແຂວງ, ນະຄອນຫຼວງ'),
	(736, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມຊັ້ນ-ຂັ້ນເງິນເດືອນ ແຕ່ຊັ້ນ I ເຖິງ ຊັ້ນ V'),
	(737, 'app', 'Incorrect Phiscal Year'),
	(738, 'app', 'Womwn'),
	(739, 'app', 'ພະ'),
	(740, 'app', 'ຈົວ'),
	(741, 'app', 'ພໍ່ຂາວ'),
	(742, 'app', 'ແມ່ຂາວ'),
	(743, 'app', 'ສັງກະລີ'),
	(744, 'app', 'ປະເພດ'),
	(747, 'app', 'Stat Officer Organisations Upgrade'),
	(748, 'app', 'Statistics of Document Copy'),
	(749, 'app', 'ສະຖິຕິລັດຖະກອນລວມຂອງບັນດາແຂວງ/ນະຄອນຫຼວງ'),
	(750, 'app', 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການ ຂອງບັນດາກະຊວງ, ອົງການທຽບເທົ່າ'),
	(751, 'app', 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການອົງການຈັດຕັ້ງຂັ້ນສູນກາງ'),
	(752, 'app', 'ສະຖິຕິລັດຖະກອນທີ່ເພີ່ມເຂົ້າ ແລະ ອອກທຸກຮູບການທົ່ວແຂວງ ແລະ ນະຄອນຫຼວງໃນ ສປປ ລາວ'),
	(753, 'app', 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນກະຊວງທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(754, 'app', 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນອົງການທຽບເທົ່າທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(755, 'app', 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນທ້ອງຖິ່ນທີ່ໄປເຝິກອົບຮົມ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(756, 'app', 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນກະຊວງທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(757, 'app', 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນອົງການທຽບເທົ່າທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(758, 'app', 'ສະຖິຕິພະນັກງານລັດຖະກອນຂັ້ນທ້ອງຖິ່ນທີ່ໄປຍົກລະດັບ ຢູ່ພາຍໃນ ແລະ ຕ່າງປະເທດ'),
	(759, 'app', 'ສະຖາບັນຮ່ວມກັບພາກສ່ວນພາຍນອກຈັດເຝິກອົບຮົມ'),
	(760, 'app', 'ສະຖິຕິສັງລວມສະຖາບັນຈັດກອງປະຊຸມ ແລະ ຝຶກອົບຮົມໃຫ້ບັນດາກະຊວງ, ອົງການຂັ້ນສູນກາງ ແລະ ທ້ອງຖິ່ນ'),
	(761, 'app', 'ປະເພດຫຼຽນກາຕ່າງໆ ແລະ ໃບຍ້ອງຍໍລັດຖະບານ ສຳລັບຍ້ອງຍໍຕ່າງປະເທດຂອງບັນດາແຂວງ, ນະຄອນຫຼວງວຽງຈັນ'),
	(762, 'app', 'ສະຖິຕິໂຄງການລົງທຶນຂອງລັດ'),
	(763, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນ ແຍກຕາມວິຊາສະເພາະ'),
	(764, 'app', 'ຕາຕະລາງສັງລວມຈຳນວນລັດຖະກອນແຍກຕາມເກນອາຍຸ'),
	(765, 'app', 'ຕາຕະລາງຈຳນວນລັດຖະກອນແຍກຕາມຊົນເຜົ່າ'),
	(766, 'app', 'ສະຖິຕິຜູ້ທີ່ໄດ້ຮັບຕຳແໜ່ງບໍລິຫານປະເພດຕ່າງໆ'),
	(767, 'app', 'ຈຳນວນລັດຖະກອນເພີ່ມເຂົ້າໃໝ່ໃນຮູບການຕ່າງໆ'),
	(768, 'app', 'ຕາຕະລາງສັງລວມ ພະນັກງານຕາມສັນຍາ'),
	(769, 'app', 'ຕາຕະລາງບັນຊີໂຄງການຊ່ວຍເຫຼືອທາງການເພື່ອການພັດທະນາ'),
	(770, 'app', 'Stat Officer Ethnics'),
	(771, 'app', 'Create Stat Officer Ethnic'),
	(772, 'app', 'Stat Positions'),
	(773, 'app', 'Create Stat Position'),
	(774, 'app', 'Stat Officer News'),
	(775, 'app', 'Create Stat Officer New'),
	(776, 'app', 'ກົມ'),
	(777, 'app', 'User Name'),
	(778, 'app', 'First Name'),
	(779, 'app', 'Last Name'),
	(780, 'app', 'Telephone'),
	(781, 'app', 'Email'),
	(782, 'app', 'Role'),
	(783, 'app', 'Input Date Time Stamp'),
	(784, 'app', 'Plase select'),
	(785, 'app', 'Add Role'),
	(786, 'app', 'Add Record'),
	(787, 'app', 'Action Item(s)'),
	(788, 'app', 'Subordinate'),
	(789, 'app', 'Selecct All'),
	(790, 'app', 'Stat Odas'),
	(804, 'app', 'Clear'),
	(805, 'app', 'Incorrect Request'),
	(806, 'app', 'Data Not Found'),
	(807, 'app', 'Is Province'),
	(808, 'app', 'Is Province Role'),
	(809, 'app', 'Save Role'),
	(810, 'app', 'Update Role'),
	(811, 'app', 'Delete Role'),
	(812, 'app', 'Subordinate(s)'),
	(813, 'app', 'Department(s)'),
	(814, 'app', 'Province(s)'),
	(815, 'app', 'User List'),
	(816, 'app', 'Select All'),
	(817, 'app', 'Department List'),
	(818, 'app', 'Data has been save success fully!'),
	(819, 'app', 'Unauthorized'),
	(820, 'app', 'HTTP Error 401 Unauthorized operation'),
	(821, 'app', 'You are not authorized to access this page due to invalid authentication'),
	(822, 'app', 'Please contact administrator'),
	(823, 'app', 'ທັງໝົດ'),
	(824, 'app', 'ບໍ່ອະນຸຍາດ'),
	(825, 'app', 'HTTP Error 401- You are not authorized to access this operaton due to invalid authentication'),
	(826, 'app', 'Subordinate List'),
	(827, 'app', 'Province Code'),
	(828, 'app', 'Province Name'),
	(829, 'app', 'Record Status'),
	(830, 'app', 'Input ID'),
	(831, 'app', 'ລະຫັດ'),
	(832, 'app', 'ຊື່ຜູ້ໃຊ້'),
	(833, 'app', 'ລະຫດັຜ່ານ'),
	(834, 'app', 'ຊື່ແທ້'),
	(835, 'app', 'ນາມສະກຸນ'),
	(836, 'app', 'ສະຖານະ'),
	(837, 'app', 'ເບີໂທ'),
	(838, 'app', 'ອີເມວ'),
	(839, 'app', 'ລຶບ'),
	(840, 'app', 'ສິດ ແລະ ໜ້າທີ່'),
	(841, 'app', 'ແຂວງ'),
	(844, 'app', 'Search:'),
	(845, 'app', 'Search Keyword'),
	(846, 'app', 'Display'),
	(847, 'app', 'records'),
	(848, 'app', 'per'),
	(849, 'app', 'page'),
	(850, 'app', 'Sorry , Nothing found'),
	(851, 'app', 'No records available'),
	(852, 'app', 'Showing'),
	(853, 'app', 'to'),
	(854, 'app', 'of'),
	(855, 'app', 'entries'),
	(856, 'app', 'filtered from'),
	(857, 'app', 'total records'),
	(858, 'app', 'First'),
	(859, 'app', 'Last'),
	(860, 'app', 'Previous'),
	(861, 'app', 'Next');
				
				
INSERT INTO `moha`.`message` (`id`, `language`, `translation`)
VALUES
	(2, 'la-LA', 'ເພີ່ມ'),
	(8, 'la-LA', 'ຂໍ້ຄວາມ'),
	(10, 'la-LA', 'ເພີ່ມ'),
	(11, 'la-LA', NULL),
	(12, 'la-LA', NULL),
	(13, 'la-LA', NULL),
	(14, 'la-LA', 'ແອັກຊັ່ນ'),
	(16, 'la-LA', ''),
	(17, 'la-LA', 'ເພີ່ມໃໝ່'),
	(18, 'la-LA', ''),
	(19, 'la-LA', ''),
	(20, 'la-LA', ''),
	(22, 'la-LA', 'asfsdfs'),
	(23, 'la-LA', 'safds'),
	(24, 'la-LA', 'sfasdf'),
	(25, 'la-LA', 'xxxx'),
	(28, 'la-LA', 'eee'),
	(29, 'la-LA', 'dd'),
	(30, 'la-LA', 'gg'),
	(32, 'la-LA', 'lpp'),
	(33, 'la-LA', ''),
	(34, 'la-LA', ''),
	(35, 'la-LA', ''),
	(36, 'la-LA', 'ທີ່ຢູ່'),
	(37, 'la-LA', ''),
	(38, 'la-LA', ''),
	(39, 'la-LA', 'ສະຖິຕິບັນດາຫົວໜ່ວຍການຈັດຕັ້ງ (ກົມ ແລະ ອົງການລັດທຽບເທົ່າກົມ)'),
	(40, 'la-LA', ''),
	(41, 'la-LA', ''),
	(42, 'la-LA', ''),
	(43, 'la-LA', 'ວັນທີເລີ່ມ'),
	(44, 'la-LA', 'ວັນທີສຳເລັດ'),
	(45, 'la-LA', 'ສະຖານະ'),
	(46, 'la-LA', 'ປິດ'),
	(47, 'la-LA', ''),
	(48, 'la-LA', 'ລຶບ'),
	(49, 'la-LA', 'ທ່ານຕ້ອງການລຶບຂໍ້ມູນນີ້ບໍ່?'),
	(50, 'la-LA', ''),
	(51, 'la-LA', ''),
	(52, 'la-LA', 'ປີ'),
	(53, 'la-LA', ''),
	(54, 'la-LA', ''),
	(55, 'la-LA', 'ກະຊວງ'),
	(56, 'la-LA', ''),
	(57, 'la-LA', ''),
	(58, 'la-LA', ''),
	(59, 'la-LA', ''),
	(60, 'la-LA', 'ເພີ່ມໃໝ່'),
	(61, 'la-LA', 'ບັນທຶກ'),
	(62, 'la-LA', ''),
	(63, 'la-LA', ''),
	(64, 'la-LA', ''),
	(65, 'la-LA', 'ລວມ'),
	(66, 'la-LA', ''),
	(67, 'la-LA', ''),
	(68, 'la-LA', ''),
	(69, 'la-LA', ''),
	(70, 'la-LA', ''),
	(71, 'la-LA', ''),
	(72, 'la-LA', ''),
	(73, 'la-LA', ''),
	(74, 'la-LA', ''),
	(75, 'la-LA', ''),
	(76, 'la-LA', ''),
	(77, 'la-LA', ''),
	(78, 'la-LA', ''),
	(79, 'la-LA', ''),
	(80, 'la-LA', ''),
	(81, 'la-LA', 'ລ/ດ'),
	(82, 'la-LA', 'ໝາຍເຫດ'),
	(83, 'la-LA', ''),
	(84, 'la-LA', ''),
	(85, 'la-LA', ''),
	(86, 'la-LA', ''),
	(87, 'la-LA', ''),
	(88, 'la-LA', ''),
	(89, 'la-LA', ''),
	(90, 'la-LA', ''),
	(91, 'la-LA', ''),
	(92, 'la-LA', ''),
	(93, 'la-LA', ''),
	(101, 'la-LA', ''),
	(102, 'la-LA', 'ກົມ'),
	(103, 'la-LA', 'ສະຖາບັນ'),
	(104, 'la-LA', 'ສູນ'),
	(105, 'la-LA', 'ສະຖາບັນ'),
	(106, 'la-LA', ''),
	(107, 'la-LA', ''),
	(108, 'la-LA', ''),
	(110, 'la-LA', 'ຫ້ອງການ'),
	(111, 'la-LA', ''),
	(112, 'la-LA', ''),
	(113, 'la-LA', 'ສະຖິຕິໜ່ວຍງານຈັດຕັ້ງປະຕິບັດກົນໄກການບໍລິການຜ່ານປະຕູດຽວ'),
	(114, 'la-LA', 'ຊື່ໜ່ວຍງານ'),
	(115, 'la-LA', ''),
	(116, 'la-LA', ''),
	(117, 'la-LA', ''),
	(118, 'la-LA', ''),
	(119, 'la-LA', ''),
	(120, 'la-LA', ''),
	(121, 'la-LA', ''),
	(122, 'la-LA', ''),
	(123, 'la-LA', ''),
	(124, 'la-LA', ''),
	(125, 'la-LA', ''),
	(126, 'la-LA', ''),
	(127, 'la-LA', ''),
	(128, 'la-LA', ''),
	(131, 'la-LA', ''),
	(132, 'la-LA', ''),
	(133, 'la-LA', ''),
	(134, 'la-LA', ''),
	(135, 'la-LA', 'ໄອດີຜູ້ອານຸມັດ'),
	(136, 'la-LA', 'ຂັ້ນຜູ້ອະນຸມັດ'),
	(137, 'la-LA', 'ຜູ້ອະນຸມັດ'),
	(138, 'la-LA', 'ຜູ້ອະນຸມັດ'),
	(139, 'la-LA', ''),
	(140, 'la-LA', 'ຂັ້ນຜູ້ອະນຸມັດ'),
	(141, 'la-LA', ''),
	(142, 'la-LA', 'ແຂວງ'),
	(143, 'la-LA', 'ສະຖິຕິສະມາຄົມ/ມູນນິທິ ໃນທົ່ວປະເທດ'),
	(144, 'la-LA', ''),
	(145, 'la-LA', 'ສະຖິຕິສະມາຄົມ/ມູນນິທິ ໃນທົ່ວປະເທດ'),
	(146, 'la-LA', 'ສະຖິຕິສະມາຄົມ/ມູນນິທິ ໃນທົ່ວປະເທດ'),
	(147, 'la-LA', 'ສະມາຄົມ'),
	(148, 'la-LA', 'ມູນນິທິ'),
	(149, 'la-LA', ''),
	(150, 'la-LA', 'ມູນນິທິ'),
	(151, 'la-LA', ''),
	(152, 'la-LA', ''),
	(153, 'la-LA', ''),
	(154, 'la-LA', ''),
	(155, 'la-LA', ''),
	(156, 'la-LA', ''),
	(157, 'la-LA', 'ລ'),
	(158, 'la-LA', 'ຍ'),
	(159, 'la-LA', ''),
	(160, 'la-LA', ''),
	(161, 'la-LA', 'ຈຳນວນປພົນລະເມືອງ'),
	(162, 'la-LA', 'ບ້ານ'),
	(163, 'la-LA', ''),
	(164, 'la-LA', ''),
	(165, 'la-LA', ''),
	(166, 'la-LA', 'ສະມາຄົມ/ມູນນິທິ'),
	(167, 'la-LA', ''),
	(168, 'la-LA', ''),
	(169, 'la-LA', ''),
	(170, 'la-LA', ''),
	(171, 'la-LA', 'ເມືອງ'),
	(172, 'la-LA', 'ຈຳນວນເກີດ'),
	(173, 'la-LA', 'ຈຳນວນເສຍຊີວິດ'),
	(174, 'la-LA', 'ແຕ່ງດອງ'),
	(175, 'la-LA', 'ຢ່າຮ້າງ'),
	(176, 'la-LA', 'ຍ້າຍມາ'),
	(177, 'la-LA', 'ຍ້າຍອອກໄປ'),
	(178, 'la-LA', 'ຈຳນວນພົນລະເມືອງ ທີ່ມີໜ້າຕົວຈິງ'),
	(179, 'la-LA', ''),
	(180, 'la-LA', ''),
	(181, 'la-LA', ''),
	(182, 'la-LA', ''),
	(183, 'la-LA', ''),
	(184, 'la-LA', ''),
	(185, 'la-LA', ''),
	(186, 'la-LA', ''),
	(187, 'la-LA', ''),
	(188, 'la-LA', ''),
	(189, 'la-LA', ''),
	(190, 'la-LA', ''),
	(191, 'la-LA', ''),
	(192, 'la-LA', ''),
	(193, 'la-LA', ''),
	(194, 'la-LA', ''),
	(195, 'la-LA', ''),
	(196, 'la-LA', 'ຍິງ'),
	(197, 'la-LA', ''),
	(198, 'la-LA', ''),
	(199, 'la-LA', ''),
	(200, 'la-LA', ''),
	(201, 'la-LA', ''),
	(202, 'la-LA', ''),
	(203, 'la-LA', ''),
	(204, 'la-LA', 'ຊົນເຜົ່າ'),
	(205, 'la-LA', ''),
	(206, 'la-LA', 'ຊົນເຜົ່າ'),
	(207, 'la-LA', ''),
	(208, 'la-LA', ''),
	(209, 'la-LA', ''),
	(210, 'la-LA', ''),
	(211, 'la-LA', ''),
	(212, 'la-LA', ''),
	(213, 'la-LA', ''),
	(214, 'la-LA', ''),
	(215, 'la-LA', ''),
	(216, 'la-LA', ''),
	(217, 'la-LA', ''),
	(218, 'la-LA', ''),
	(219, 'la-LA', ''),
	(220, 'la-LA', ''),
	(221, 'la-LA', ''),
	(222, 'la-LA', ''),
	(223, 'la-LA', ''),
	(224, 'la-LA', ''),
	(225, 'la-LA', ''),
	(226, 'la-LA', ''),
	(227, 'la-LA', ''),
	(228, 'la-LA', ''),
	(229, 'la-LA', ''),
	(230, 'la-LA', ''),
	(231, 'la-LA', ''),
	(232, 'la-LA', 'ລາຍການ'),
	(233, 'la-LA', ''),
	(234, 'la-LA', 'ຊາຍ'),
	(235, 'la-LA', ''),
	(236, 'la-LA', ''),
	(237, 'la-LA', ''),
	(238, 'la-LA', ''),
	(239, 'la-LA', ''),
	(240, 'la-LA', ''),
	(241, 'la-LA', ''),
	(242, 'la-LA', ''),
	(243, 'la-LA', ''),
	(244, 'la-LA', ''),
	(245, 'la-LA', ''),
	(246, 'la-LA', ''),
	(247, 'la-LA', ''),
	(248, 'la-LA', ''),
	(249, 'la-LA', ''),
	(250, 'la-LA', ''),
	(251, 'la-LA', ''),
	(252, 'la-LA', ''),
	(253, 'la-LA', ''),
	(254, 'la-LA', ''),
	(255, 'la-LA', ''),
	(256, 'la-LA', ''),
	(257, 'la-LA', 'ລາອອກ'),
	(258, 'la-LA', ''),
	(259, 'la-LA', ''),
	(260, 'la-LA', ''),
	(261, 'la-LA', ''),
	(262, 'la-LA', ''),
	(263, 'la-LA', ''),
	(264, 'la-LA', ''),
	(265, 'la-LA', ''),
	(266, 'la-LA', ''),
	(267, 'la-LA', ''),
	(268, 'la-LA', ''),
	(269, 'la-LA', ''),
	(270, 'la-LA', ''),
	(271, 'la-LA', ''),
	(272, 'la-LA', ''),
	(273, 'la-LA', ''),
	(274, 'la-LA', ''),
	(275, 'la-LA', ''),
	(276, 'la-LA', ''),
	(277, 'la-LA', ''),
	(278, 'la-LA', ''),
	(279, 'la-LA', ''),
	(280, 'la-LA', ''),
	(281, 'la-LA', ''),
	(282, 'la-LA', ''),
	(283, 'la-LA', ''),
	(284, 'la-LA', ''),
	(285, 'la-LA', ''),
	(286, 'la-LA', ''),
	(287, 'la-LA', ''),
	(288, 'la-LA', ''),
	(289, 'la-LA', ''),
	(290, 'la-LA', ''),
	(293, 'la-LA', ''),
	(294, 'la-LA', ''),
	(295, 'la-LA', ''),
	(296, 'la-LA', ''),
	(297, 'la-LA', ''),
	(298, 'la-LA', ''),
	(299, 'la-LA', ''),
	(300, 'la-LA', ''),
	(301, 'la-LA', ''),
	(302, 'la-LA', ''),
	(303, 'la-LA', ''),
	(308, 'la-LA', ''),
	(309, 'la-LA', ''),
	(310, 'la-LA', ''),
	(311, 'la-LA', ''),
	(312, 'la-LA', ''),
	(313, 'la-LA', 'ຝຶກອົບຮົມວິຊາສະເພາະ'),
	(314, 'la-LA', 'ຝຶກອົບຮົມວິຊາທິດສະດີ'),
	(315, 'la-LA', 'ພາຍໃນ'),
	(316, 'la-LA', 'ຕ່າງປະເທດ'),
	(317, 'la-LA', ''),
	(318, 'la-LA', ''),
	(319, 'la-LA', ''),
	(320, 'la-LA', ''),
	(321, 'la-LA', ''),
	(322, 'la-LA', ''),
	(330, 'la-LA', ''),
	(331, 'la-LA', ''),
	(332, 'la-LA', ''),
	(333, 'la-LA', ''),
	(334, 'la-LA', ''),
	(335, 'la-LA', ''),
	(336, 'la-LA', ''),
	(337, 'la-LA', ''),
	(338, 'la-LA', ''),
	(339, 'la-LA', ''),
	(340, 'la-LA', ''),
	(341, 'la-LA', ''),
	(342, 'la-LA', ''),
	(343, 'la-LA', ''),
	(344, 'la-LA', ''),
	(345, 'la-LA', ''),
	(346, 'la-LA', ''),
	(347, 'la-LA', ''),
	(348, 'la-LA', ''),
	(349, 'la-LA', ''),
	(350, 'la-LA', ''),
	(351, 'la-LA', ''),
	(352, 'la-LA', ''),
	(353, 'la-LA', ''),
	(354, 'la-LA', ''),
	(355, 'la-LA', ''),
	(356, 'la-LA', ''),
	(357, 'la-LA', ''),
	(358, 'la-LA', ''),
	(359, 'la-LA', ''),
	(360, 'la-LA', ''),
	(361, 'la-LA', ''),
	(362, 'la-LA', ''),
	(363, 'la-LA', ''),
	(364, 'la-LA', ''),
	(365, 'la-LA', ''),
	(366, 'la-LA', ''),
	(367, 'la-LA', ''),
	(368, 'la-LA', ''),
	(369, 'la-LA', ''),
	(370, 'la-LA', ''),
	(371, 'la-LA', ''),
	(372, 'la-LA', ''),
	(374, 'la-LA', ''),
	(375, 'la-LA', ''),
	(376, 'la-LA', ''),
	(377, 'la-LA', ''),
	(378, 'la-LA', ''),
	(379, 'la-LA', ''),
	(380, 'la-LA', ''),
	(381, 'la-LA', ''),
	(382, 'la-LA', ''),
	(383, 'la-LA', ''),
	(384, 'la-LA', ''),
	(385, 'la-LA', ''),
	(386, 'la-LA', ''),
	(387, 'la-LA', ''),
	(388, 'la-LA', ''),
	(389, 'la-LA', ''),
	(390, 'la-LA', ''),
	(391, 'la-LA', ''),
	(392, 'la-LA', ''),
	(394, 'la-LA', ''),
	(395, 'la-LA', ''),
	(396, 'la-LA', ''),
	(398, 'la-LA', ''),
	(399, 'la-LA', ''),
	(400, 'la-LA', 'ຍ້ອງຍໍຜົນງານ'),
	(437, 'la-LA', ''),
	(438, 'la-LA', ''),
	(439, 'la-LA', ''),
	(440, 'la-LA', ''),
	(441, 'la-LA', ''),
	(442, 'la-LA', ''),
	(443, 'la-LA', ''),
	(444, 'la-LA', ''),
	(445, 'la-LA', ''),
	(446, 'la-LA', ''),
	(447, 'la-LA', ''),
	(448, 'la-LA', ''),
	(477, 'la-LA', ''),
	(478, 'la-LA', ''),
	(479, 'la-LA', ''),
	(480, 'la-LA', ''),
	(481, 'la-LA', ''),
	(482, 'la-LA', ''),
	(483, 'la-LA', ''),
	(484, 'la-LA', ''),
	(485, 'la-LA', ''),
	(486, 'la-LA', ''),
	(487, 'la-LA', ''),
	(488, 'la-LA', ''),
	(489, 'la-LA', ''),
	(490, 'la-LA', ''),
	(491, 'la-LA', ''),
	(492, 'la-LA', ''),
	(493, 'la-LA', ''),
	(500, 'la-LA', ''),
	(501, 'la-LA', ''),
	(502, 'la-LA', 'ການເຄື່ອນໄຫວ'),
	(503, 'la-LA', ''),
	(504, 'la-LA', ''),
	(505, 'la-LA', ''),
	(506, 'la-LA', ''),
	(507, 'la-LA', ''),
	(508, 'la-LA', ''),
	(514, 'la-LA', ''),
	(515, 'la-LA', ''),
	(516, 'la-LA', ''),
	(517, 'la-LA', ''),
	(518, 'la-LA', ''),
	(519, 'la-LA', ''),
	(520, 'la-LA', ''),
	(521, 'la-LA', ''),
	(522, 'la-LA', ''),
	(523, 'la-LA', ''),
	(524, 'la-LA', ''),
	(525, 'la-LA', ''),
	(526, 'la-LA', ''),
	(527, 'la-LA', ''),
	(528, 'la-LA', ''),
	(529, 'la-LA', ''),
	(530, 'la-LA', ''),
	(531, 'la-LA', ''),
	(532, 'la-LA', ''),
	(533, 'la-LA', ''),
	(534, 'la-LA', ''),
	(535, 'la-LA', ''),
	(536, 'la-LA', ''),
	(537, 'la-LA', ''),
	(538, 'la-LA', ''),
	(539, 'la-LA', ''),
	(540, 'la-LA', ''),
	(541, 'la-LA', ''),
	(542, 'la-LA', ''),
	(543, 'la-LA', ''),
	(544, 'la-LA', ''),
	(545, 'la-LA', ''),
	(546, 'la-LA', ''),
	(547, 'la-LA', ''),
	(548, 'la-LA', ''),
	(549, 'la-LA', ''),
	(550, 'la-LA', ''),
	(551, 'la-LA', ''),
	(552, 'la-LA', ''),
	(553, 'la-LA', ''),
	(554, 'la-LA', ''),
	(555, 'la-LA', ''),
	(556, 'la-LA', ''),
	(557, 'la-LA', ''),
	(558, 'la-LA', ''),
	(559, 'la-LA', ''),
	(560, 'la-LA', ''),
	(561, 'la-LA', ''),
	(562, 'la-LA', ''),
	(563, 'la-LA', ''),
	(564, 'la-LA', ''),
	(565, 'la-LA', ''),
	(566, 'la-LA', ''),
	(567, 'la-LA', ''),
	(568, 'la-LA', ''),
	(569, 'la-LA', ''),
	(570, 'la-LA', ''),
	(571, 'la-LA', ''),
	(572, 'la-LA', ''),
	(573, 'la-LA', ''),
	(574, 'la-LA', ''),
	(575, 'la-LA', ''),
	(576, 'la-LA', ''),
	(577, 'la-LA', ''),
	(578, 'la-LA', ''),
	(579, 'la-LA', ''),
	(580, 'la-LA', ''),
	(581, 'la-LA', ''),
	(582, 'la-LA', ''),
	(583, 'la-LA', ''),
	(584, 'la-LA', ''),
	(585, 'la-LA', ''),
	(586, 'la-LA', ''),
	(587, 'la-LA', ''),
	(588, 'la-LA', ''),
	(589, 'la-LA', ''),
	(590, 'la-LA', ''),
	(591, 'la-LA', ''),
	(592, 'la-LA', ''),
	(593, 'la-LA', ''),
	(594, 'la-LA', ''),
	(595, 'la-LA', ''),
	(596, 'la-LA', ''),
	(597, 'la-LA', ''),
	(598, 'la-LA', ''),
	(599, 'la-LA', ''),
	(600, 'la-LA', ''),
	(601, 'la-LA', ''),
	(602, 'la-LA', ''),
	(603, 'la-LA', ''),
	(604, 'la-LA', ''),
	(605, 'la-LA', ''),
	(606, 'la-LA', ''),
	(607, 'la-LA', ''),
	(608, 'la-LA', ''),
	(609, 'la-LA', ''),
	(610, 'la-LA', ''),
	(611, 'la-LA', ''),
	(612, 'la-LA', ''),
	(613, 'la-LA', ''),
	(614, 'la-LA', ''),
	(615, 'la-LA', ''),
	(616, 'la-LA', ''),
	(617, 'la-LA', ''),
	(618, 'la-LA', ''),
	(619, 'la-LA', ''),
	(620, 'la-LA', ''),
	(621, 'la-LA', ''),
	(622, 'la-LA', ''),
	(623, 'la-LA', ''),
	(624, 'la-LA', ''),
	(625, 'la-LA', ''),
	(626, 'la-LA', ''),
	(627, 'la-LA', ''),
	(628, 'la-LA', ''),
	(629, 'la-LA', ''),
	(630, 'la-LA', ''),
	(631, 'la-LA', ''),
	(632, 'la-LA', ''),
	(633, 'la-LA', ''),
	(634, 'la-LA', ''),
	(635, 'la-LA', ''),
	(636, 'la-LA', ''),
	(637, 'la-LA', ''),
	(638, 'la-LA', ''),
	(639, 'la-LA', ''),
	(640, 'la-LA', ''),
	(641, 'la-LA', ''),
	(642, 'la-LA', ''),
	(643, 'la-LA', ''),
	(644, 'la-LA', ''),
	(645, 'la-LA', ''),
	(646, 'la-LA', ''),
	(647, 'la-LA', ''),
	(648, 'la-LA', ''),
	(649, 'la-LA', ''),
	(650, 'la-LA', ''),
	(651, 'la-LA', ''),
	(652, 'la-LA', ''),
	(653, 'la-LA', ''),
	(654, 'la-LA', ''),
	(655, 'la-LA', ''),
	(656, 'la-LA', ''),
	(657, 'la-LA', ''),
	(658, 'la-LA', ''),
	(659, 'la-LA', ''),
	(660, 'la-LA', ''),
	(661, 'la-LA', ''),
	(662, 'la-LA', ''),
	(663, 'la-LA', ''),
	(664, 'la-LA', ''),
	(665, 'la-LA', ''),
	(666, 'la-LA', ''),
	(667, 'la-LA', ''),
	(668, 'la-LA', ''),
	(669, 'la-LA', ''),
	(670, 'la-LA', ''),
	(671, 'la-LA', ''),
	(672, 'la-LA', ''),
	(673, 'la-LA', ''),
	(674, 'la-LA', ''),
	(675, 'la-LA', ''),
	(676, 'la-LA', ''),
	(677, 'la-LA', ''),
	(678, 'la-LA', ''),
	(679, 'la-LA', ''),
	(680, 'la-LA', ''),
	(681, 'la-LA', ''),
	(682, 'la-LA', ''),
	(683, 'la-LA', ''),
	(684, 'la-LA', ''),
	(685, 'la-LA', ''),
	(686, 'la-LA', ''),
	(687, 'la-LA', ''),
	(688, 'la-LA', ''),
	(689, 'la-LA', ''),
	(690, 'la-LA', ''),
	(691, 'la-LA', ''),
	(692, 'la-LA', ''),
	(693, 'la-LA', ''),
	(694, 'la-LA', ''),
	(695, 'la-LA', ''),
	(696, 'la-LA', ''),
	(697, 'la-LA', ''),
	(698, 'la-LA', ''),
	(699, 'la-LA', ''),
	(700, 'la-LA', ''),
	(701, 'la-LA', ''),
	(702, 'la-LA', ''),
	(703, 'la-LA', ''),
	(704, 'la-LA', 'ຊື່ບົດບາດ'),
	(705, 'la-LA', 'ສ້າງວັນທີ / ເວລາ'),
	(706, 'la-LA', ''),
	(707, 'la-LA', 'ລາຍການເມນູ'),
	(708, 'la-LA', ''),
	(709, 'la-LA', ''),
	(710, 'la-LA', ''),
	(711, 'la-LA', ''),
	(712, 'la-LA', ''),
	(713, 'la-LA', ''),
	(714, 'la-LA', ''),
	(715, 'la-LA', ''),
	(716, 'la-LA', ''),
	(717, 'la-LA', ''),
	(718, 'la-LA', ''),
	(719, 'la-LA', ''),
	(720, 'la-LA', ''),
	(721, 'la-LA', ''),
	(722, 'la-LA', ''),
	(723, 'la-LA', ''),
	(724, 'la-LA', ''),
	(725, 'la-LA', ''),
	(726, 'la-LA', ''),
	(727, 'la-LA', ''),
	(728, 'la-LA', ''),
	(729, 'la-LA', ''),
	(730, 'la-LA', ''),
	(731, 'la-LA', ''),
	(732, 'la-LA', ''),
	(733, 'la-LA', ''),
	(734, 'la-LA', ''),
	(735, 'la-LA', ''),
	(736, 'la-LA', ''),
	(737, 'la-LA', ''),
	(738, 'la-LA', ''),
	(739, 'la-LA', ''),
	(740, 'la-LA', ''),
	(741, 'la-LA', ''),
	(742, 'la-LA', ''),
	(743, 'la-LA', ''),
	(744, 'la-LA', ''),
	(747, 'la-LA', ''),
	(748, 'la-LA', ''),
	(749, 'la-LA', ''),
	(750, 'la-LA', ''),
	(751, 'la-LA', ''),
	(752, 'la-LA', ''),
	(753, 'la-LA', ''),
	(754, 'la-LA', ''),
	(755, 'la-LA', ''),
	(756, 'la-LA', ''),
	(757, 'la-LA', ''),
	(758, 'la-LA', ''),
	(759, 'la-LA', ''),
	(760, 'la-LA', ''),
	(761, 'la-LA', ''),
	(762, 'la-LA', ''),
	(763, 'la-LA', ''),
	(764, 'la-LA', ''),
	(765, 'la-LA', ''),
	(766, 'la-LA', ''),
	(767, 'la-LA', ''),
	(768, 'la-LA', ''),
	(769, 'la-LA', ''),
	(770, 'la-LA', ''),
	(771, 'la-LA', ''),
	(772, 'la-LA', ''),
	(773, 'la-LA', ''),
	(774, 'la-LA', ''),
	(775, 'la-LA', ''),
	(776, 'la-LA', ''),
	(777, 'la-LA', 'ຊື່ໃຊ້ລະບົບ'),
	(778, 'la-LA', 'ຊື່'),
	(779, 'la-LA', 'ນາມສະກຸນ'),
	(780, 'la-LA', 'ໂທລະສັບ'),
	(781, 'la-LA', 'ອີເມວລ'),
	(782, 'la-LA', 'ສິດ'),
	(783, 'la-LA', ''),
	(784, 'la-LA', ''),
	(785, 'la-LA', 'ເພີ່ມສິດ'),
	(786, 'la-LA', 'ເພີ່ມ'),
	(787, 'la-LA', 'ລາຍການຟັງຊັ່ນຕ່າງໆ'),
	(788, 'la-LA', 'ຜູ້ໃຊ້ທີ່ຂື້ນກັບ'),
	(789, 'la-LA', ''),
	(790, 'la-LA', ''),
	(804, 'la-LA', ''),
	(805, 'la-LA', ''),
	(806, 'la-LA', ''),
	(807, 'la-LA', 'ສິດຂັ້ນແຂວງບໍ່?'),
	(808, 'la-LA', 'ສິດຂັ້ນແຂວງບໍ່?'),
	(809, 'la-LA', 'ບັນທຶກບົດບາດ'),
	(810, 'la-LA', 'ແກ້ໄຂບົດບາດ'),
	(811, 'la-LA', 'ລຶບບົດບາດ'),
	(812, 'la-LA', 'ລາຍຊື່ຜູ້ໃຊ້ທີ່ຂື້ນກັບ'),
	(813, 'la-LA', 'ບັນດາກົມ'),
	(814, 'la-LA', 'ບັນດາແຂວງ'),
	(815, 'la-LA', ''),
	(816, 'la-LA', 'ເລືອກທັງໝົດ'),
	(817, 'la-LA', 'ລາຍຊື່ກົມ'),
	(818, 'la-LA', ''),
	(819, 'la-LA', ''),
	(820, 'la-LA', ''),
	(821, 'la-LA', ''),
	(822, 'la-LA', ''),
	(823, 'la-LA', ''),
	(824, 'la-LA', ''),
	(825, 'la-LA', ''),
	(826, 'la-LA', 'ລາຍຊື່ຜູ້ໃຊ້ທີ່ຂື້ນກັບ'),
	(827, 'la-LA', 'ລະຫັດແຂວງ'),
	(828, 'la-LA', 'ຊື່ແຂວງ'),
	(829, 'la-LA', ''),
	(830, 'la-LA', ''),
	(831, 'la-LA', ''),
	(832, 'la-LA', ''),
	(833, 'la-LA', ''),
	(834, 'la-LA', ''),
	(835, 'la-LA', ''),
	(836, 'la-LA', ''),
	(837, 'la-LA', ''),
	(838, 'la-LA', ''),
	(839, 'la-LA', ''),
	(840, 'la-LA', ''),
	(841, 'la-LA', ''),
	(844, 'la-LA', 'ຄົ້ນຫາ'),
	(845, 'la-LA', 'ຄໍາສັບໃນການຄົ້ນຫາ'),
	(846, 'la-LA', 'ສະແດງ'),
	(847, 'la-LA', 'ແຖວ'),
	(848, 'la-LA', 'ຕໍ່'),
	(849, 'la-LA', 'ໜຶ່ງໜ້າ'),
	(850, 'la-LA', 'ຂໍອາໄພ , ບໍ່ພົບຂໍ້ມູນໃນການຄົົ້ນຫາ'),
	(851, 'la-LA', 'ບໍ່ມີຂໍ້ມູນ'),
	(852, 'la-LA', 'ສະແດງ'),
	(853, 'la-LA', 'ເຖິງ'),
	(854, 'la-LA', 'ຂອງ'),
	(855, 'la-LA', 'ທັງໝົດ'),
	(856, 'la-LA', 'ຄົ້ນຫາຈາກ'),
	(857, 'la-LA', 'ຂໍ້ມູນທັງໝົດ'),
	(858, 'la-LA', 'ທໍາອິດ'),
	(859, 'la-LA', 'ສຸດທ້າຍ'),
	(860, 'la-LA', 'ກ່ອນໜ້າ'),
	(861, 'la-LA', 'ຕໍ່ໄປ');
				
				
	        set foreign_key_checks=1;
            ";
		$this->execute($sql);
	}
	public function safeDown()
	{
		$sql = "
            set foreign_key_checks=0;
   			TRUNCATE TABLE  `moha`.`menu`;
			TRUNCATE TABLE  `moha`.`message`;
			TRUNCATE TABLE  `moha`.`source_message`;			
            set foreign_key_checks=1;
            ";
		$this->execute($sql);
	}
}
