<?php

namespace app\controllers;

use app\components\MyHelper;
use Yii;
use app\models\Govermentlevel;
use app\models\GovermentlevelSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GovermentlevelController implements the CRUD actions for Govermentlevel model.
 */
class GovermentlevelController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Govermentlevel models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render("index");
    }

    /**
     * Displays a single Govermentlevel model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Govermentlevel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Govermentlevel();
        $post = Yii::$app->request->post();
        if (!$model->load($post))
            return json_encode(["error" => Yii::t('app', 'Parse Error') . " ". json_encode($post)]);

        if(!$model->save())
            return json_encode(["error" => $model->errors]);

        return json_encode(["model" => $model->attributes]);
    }

    /**
     * Updates an existing Govermentlevel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionGetall() {
        return json_encode(
            Govermentlevel::find(["deleleted" => 0])
                ->asArray()
                ->all());
    }

    /**
     * Deletes an existing Govermentlevel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Govermentlevel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Govermentlevel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Govermentlevel::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
