<?php

namespace app\controllers;

use app\models\SourceMessage;
use Yii;
use app\models\Message;
use yii\db\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MessageController implements the CRUD actions for Message model.
 */
class MessageController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Message models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render("index");
    }

    /**
     * Creates a new Message model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Message();
        $post = Yii::$app->request->post();
        if (!$model->load($post))
            return json_encode(["error" => Yii::t('app', 'Parse Error') . " " . json_encode($post)]);

        $db = Yii::$app->db->beginTransaction();
        try {
            $sourceMessage = new SourceMessage();
            $sourceMessage->message = $post["Message"]["message"];
            $sourceMessage->category = 'app';
            if(!$sourceMessage->save())
                throw new Exception(json_encode($sourceMessage->errors));

            $model->id = $sourceMessage->id;
            $model->language = "la-LA";
            if(!$model->save())
                return json_encode(["error" => $model->errors]);

            $model->id = "$model->id";
            $db->commit();
            return json_encode(["model" => array_merge($model->attributes, [
                "message" => $sourceMessage->message,
                "category" => $sourceMessage->category
            ])]);
        } catch (Exception $exception) {
            $db->rollBack();
            return json_encode(['error' => $exception->getTraceAsString()]);
        }
    }

    /**
     * Updates an existing Message model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param string $language
     * @return mixed
     */
    public function actionUpdate($id, $language = "la-LA") {
        $model = $this->findModel($id, $language);
        $post = Yii::$app->request->post();
        if (!$model->load($post))
            return json_encode(['error' => print_r($post, true)]);

        if(!$model->save())
            return json_encode(['error' => $model->errors]);

        return json_encode(["model" => $model->attributes]);

    }

    public function actionGetall() {
        return json_encode(
            Message::find(["deleleted" => 0])
                ->select("*")
                ->join("join", "source_message s", "s.id = message.id")
            ->asArray()
            ->all());
    }

    /**
     * Deletes an existing Message model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param string $language
     * @return mixed
     */
    public function actionDelete()
    {
        $post = Yii::$app->request->post();
        if(isset($post)) {
            if(!$this->findModel($post['id'], 'la-LA')->delete())
                return json_encode(["error" => Yii::t('app','Cannot Delete')]);
            else
                return json_encode(["message" => "OK"]);
        } else
            return json_encode(["error" => Yii::t('app','Incorrect Requested')]);
    }

    /**
     * Finds the Message model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param string $language
     * @return Message the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $language)
    {
        if (($model = Message::findOne(['id' => $id, 'language' => $language])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
