<?php

namespace app\models;

use app\components\MyHelper;
use Yii;

/**
 * This is the model class for table "notice".
 *
 * @property int $id
 * @property string $created_date
 * @property string $title
 * @property string $content
 * @property string $start_date
 * @property string $end_date
 * @property int $show
 * @property int $user_id
 * @property int $position
 *
 * @property User $user
 */
class Notice extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notice';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_date', 'title', 'start_date', 'end_date', 'user_id'], 'required'],
            [['created_date', 'start_date', 'end_date'], 'safe'],
            [['content'], 'string'],
            [['show', 'user_id', 'position'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'created_date' => 'ວັນທີ່ສ້າງ',
            'title' => 'ຫົວຂໍ້',
            'content' => 'ເນື້ອໃນ',
            'start_date' => 'ວັນທີເລີ່ມ',
            'end_date' => 'ຫາວັນທີ',
            'show' => 'ສະແດງ',
            'user_id' => 'ຜູ້ໃຊ້',
            'position' => 'ຕໍາແໜ່ງ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->start_date = MyHelper::convertdatefordisplay($this->start_date);
        $this->end_date = MyHelper::convertdatefordisplay($this->end_date);
    }
}
